### ISSUE TITLE
pip installation fails for TF accessed through PYTHONPATH

### ISSUE THREAD

**Issue by David-Levinthal** [uber/horovod#132]
Due to a need to support multiple builds of tensorflow I install the wheel into a local directory and then export PYTHONPATH=~/tf_r1.4_c91_l7_py2
 python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> print (tf.__version__ )
1.4.0
>>> exit()

for reasons I do not understand I am unable to do this for the installation of horovod
and there are no instructions for installing horovod by git clone followed by some sort of python setup.py
Ubuntu 16.04, top of tree tf (R1.4), openmpi 3.0.0 (in /opt/mpi and PATH and LD_LIBRARY_PATH include the mpi install) cuda 9.1, cudnn7, nccl2 installed with dpkg
HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI PYTHONPATH=/home/levinth/tf_r1.4_c91_l7_py2 sudo pip install --no-cache-dir horovod
[sudo] password for levinth: 
Collecting horovod
  Downloading horovod-0.11.1.tar.gz (70kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 71kB 12.7MB/s 
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-TFlHfb/horovod/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Fe7xot-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops_test.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    creating build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/keras
    running build_ext
    error: import tensorflow failed, is it installed?
    
    Traceback (most recent call last):
      File "/tmp/pip-build-TFlHfb/horovod/setup.py", line 33, in check_tf_version
        import tensorflow as tf
    ImportError: No module named tensorflow
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-TFlHfb/horovod/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Fe7xot-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-TFlHfb/horovod/

could somebody enlighten me as to how I could include horovod in the enviroment? either with a correction to the pip command or with instructions on how to do the setup from source?
 I am evaluating performance of NMT codes on a set of V100s

**Comment by David-Levinthal** [comment]
invoking sudo at the beginning does a bit better but still has issues finding TF runtime?
sudo HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI PYTHONPATH=/home/levinth/tf_r1.4_c91_l7_py2 pip install --no-cache-dir horovod
[sudo] password for levinth: 
Collecting horovod
  Downloading horovod-0.11.1.tar.gz (70kB)
    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 71kB 547kB/s 
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kALdK2/horovod/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-en9ARl-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops_test.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    creating build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/keras
    running build_ext
    error: import tensorflow failed, is it installed?
    
    Traceback (most recent call last):
      File "/tmp/pip-build-kALdK2/horovod/setup.py", line 33, in check_tf_version
        import tensorflow as tf
      File "/home/levinth/tf_r1.4_c91_l7_py2/tensorflow/__init__.py", line 24, in <module>
        from tensorflow.python import *
      File "/home/levinth/tf_r1.4_c91_l7_py2/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/home/levinth/tf_r1.4_c91_l7_py2/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/home/levinth/tf_r1.4_c91_l7_py2/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/home/levinth/tf_r1.4_c91_l7_py2/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/home/levinth/tf_r1.4_c91_l7_py2/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    ImportError: libmpi.so.40: cannot open shared object file: No such file or directory
    
    
    Failed to load the native TensorFlow runtime.
    
    See https://www.tensorflow.org/install/install_sources#common_installation_problems
    
    for some common reasons and solutions.  Include the entire stack trace
    above this error message when asking for help.

**Comment by David-Levinthal** [comment]
seems I must leave out sudo.
and add variables for NCCL
HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI HOROVOD_NCCL_HOME=/usr/local/cuda/nccl HOROVOD_NCCL_INCLUDE=/usr/local/cuda/nccl/include HOROVOD_NCCL_LIB=/usr/local/cuda/nccl/lib PYTHONPATH=/home/levinth/tf_r1.4_c91_l7_py2 pip install --no-cache-dir horovod

but that did not work until I copied nccl.h into /usr/local/cuda/include  (ie /usr/local/cuda-9.1/include)

it would be good to have a set of directions for installation from source. This would have been easier
:-)

**Comment by alsrgv** [comment]
@David-Levinthal, I would recommend looking into [virtualenv](https://virtualenv.pypa.io/en/stable/).  I use them all the time, and they don't require manually setting PYTHONPATH.

**Comment by alsrgv** [comment]
Closing this issue due to inactivity.  Please feel free to re-open if you have additional questions.

**Comment by David-Levinthal** [comment]
The issue has to do with minimizing the layers of sw to get a correct hw
performance evaluation, so avoid virtualenv, docker, etc.
This is the only sw package we have encoutered where we could not jse
pythonpath.

**Comment by alsrgv** [comment]
@David-Levinthal, is it still an issue for you?  I'm not familiar with installing packages via setting PYTHONPATH.  Is this PYTHONPATH an empty directory, or you need to seed it with something, e.g. a Python installation?

Separately, AFAIK `virtualenv` does not introduce a virtualization layer and so does not have any impact on the hardware performance.  Pure convenience with no performance cost.  :-)
