### ISSUE TITLE
missing  apply_gradients function in horovod/tensorflow/__init__.py

### ISSUE THREAD

**Issue by xutaatmicrosoftdotcom** [uber/horovod#197]
I think you missed an apply_gradients function in the DistributedOptimizer class, like this:

def apply_gradients(self, *args, **kwargs):
     return self._optimizer.apply_gradients(*args, **kwargs)

Everytime I use horovod, it shows the error that _apply_dense not implemented in lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 590. The detailed error is like this:

`Traceback (most recent call last):
  File "/tmp/apprunner/.working/runtime/app/t2t-trainer.py", line 122, in <module>
    tf.app.run()
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/tmp/apprunner/.working/runtime/app/t2t-trainer.py", line 118, in main
    schedule=FLAGS.schedule)
  File "/tmp/apprunner/.working/runtime/app/tensor2tensor/utils/trainer_utils.py", line 397, in run
    hparams=hparams)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 218, in run
    return _execute_schedule(experiment, schedule)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 367, in train
    hooks=self._train_monitors + extra_hooks)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 807, in _call_train
    hooks=hooks)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 784, in _train_model
    return loss
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 4339, in get_controller
    yield default
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 784, in _train_model
    return loss
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3739, in device
    yield
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/tmp/apprunner/.working/runtime/app/tensor2tensor/utils/model_builder.py", line 336, in wrapping_model_fn
    return model_fn(model, features, mode, hparams, **kwargs)
  File "/tmp/apprunner/.working/runtime/app/tensor2tensor/utils/model_builder.py", line 297, in model_fn
    train_op = optimize.optimize(total_loss, learning_rate, hparams)
  File "/tmp/apprunner/.working/runtime/app/tensor2tensor/utils/optimize.py", line 57, in optimize
    colocate_gradients_with_ops=True)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/optimizers.py", line 302, in optimize_loss
    return train_tensor
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1844, in __exit__
    self._current_name_scope.__exit__(type_arg, value_arg, traceback_arg)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 4938, in __exit__
    self._name_scope.__exit__(type_arg, value_arg, traceback_arg)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3529, in name_scope
    yield "" if new_stack is None else new_stack + "/"
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/contrib/layers/python/layers/optimizers.py", line 297, in optimize_loss
    name="train")
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 498, in apply_gradients
    return apply_updates
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 4938, in __exit__
    self._name_scope.__exit__(type_arg, value_arg, traceback_arg)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3529, in name_scope
    yield "" if new_stack is None else new_stack + "/"
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 486, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 4938, in __exit__
    self._name_scope.__exit__(type_arg, value_arg, traceback_arg)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3529, in name_scope
    yield "" if new_stack is None else new_stack + "/"
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 486, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3660, in colocate_with
    yield
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 486, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 102, in update_op
    update_op = optimizer._apply_dense(g, self._v)  # pylint: disable=protected-access
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/horovod/tensorflow/__init__.py", line 193, in _apply_dense
    return self._optimizer._apply_dense(*args, **kwargs)
  File "/tmp/apprunner/.working/runtime/env/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 590, in _apply_dense
    raise NotImplementedError()`

So is there anything incorrect?  How do you walk around this problem?

**Comment by alsrgv** [comment]
@xutaatmicrosoftdotcom, few questions:

1. What's the version of TensorFlow that you're using?
2. Does https://github.com/uber/horovod/blob/master/examples/tensorflow_mnist_estimator.py example work in your environment?
3. Can you paste the code where you initialize optimizer, how you wrap it with `hvd.DistributedOptimizer`, and how do you use that optimizer subsequently?

The function `apply_gradients` is actually provided in the superclass that `hvd.DistributedOptimizer` is inheriting from, so I want to understand your problem deeper.

**Comment by xutaatmicrosoftdotcom** [comment]
I am so sorry it's my code bug, just ignore this issues, no need the apply_gradients function.

**Comment by alsrgv** [comment]
No worries, I will close the issue then.  Feel free to open a new one if you get another problem.
