### ISSUE TITLE
Error running Horovod

### ISSUE THREAD

**Issue by abidmalik1967** [uber/horovod#227]
I am currently running the horovod framework on different machines. On one machine I got the following message.

-----------------------
 mpirun -np 1 -H node04:1 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH python scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model resent101 --batch_size 64 --variable_update horovod
Traceback (most recent call last):
  File "scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 27, in <module>
    import benchmark_cnn
  File "/home/amalik/horovod/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 47, in <module>
    import data_utils
  File "/home/amalik/horovod/benchmarks/scripts/tf_cnn_benchmarks/data_utils.py", line 21, in <module>
    from tensorflow.contrib.data.python.ops import batching
  File "/home/amalik/.local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 84, in <module>
    from tensorflow.contrib.eager.python import tfe as eager
  File "/home/amalik/.local/lib/python2.7/site-packages/tensorflow/contrib/eager/python/tfe.py", line 78, in <module>
    from tensorflow.contrib.eager.python.datasets import Iterator
  File "/home/amalik/.local/lib/python2.7/site-packages/tensorflow/contrib/eager/python/datasets.py", line 23, in <module>
    from tensorflow.contrib.data.python.ops import prefetching_ops
  File "/home/amalik/.local/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/prefetching_ops.py", line 25, in <module>
    resource_loader.get_path_to_datafile("../../_prefetching_ops.so"))
  File "/home/amalik/.local/lib/python2.7/site-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/amalik/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/amalik/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/amalik/.local/lib/python2.7/site-packages/tensorflow/contrib/data/python/ops/../../_prefetching_ops.so: undefined symbol: _ZN6google8protobuf8internal9ArenaImpl15AllocateAlignedEm
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[40362,1],0]
  Exit code:    1
--------------------------------------------------------------------------
---------------------

Is it trying to import the data?

**Comment by alsrgv** [comment]
@abidmalik1967, this looks like a TensorFlow installation issue. Can you try installing TensorFlow in a virtual env?

**Comment by abidmalik1967** [comment]
Ok.. Will try right now!

**Comment by abidmalik1967** [comment]
@alsrgv In the virtual environment, How should I configure TF for MPI? or Horovod takes care of this and we only need simple Tensorflow installation (without MPI configuration)?

**Comment by alsrgv** [comment]
@abidmalik1967, simple TF installation should suffice. We also do embed NCCL into Horovod binary using static compilation.  You can check whether this happened by running an example with `-x NCCL_DEBUG=INFO` - you should see NCCL printing information about rings it's making.

**Comment by abidmalik1967** [comment]
@alsrgv Thanks. I was able to run it successfully. I was making a mistake as well. I was using CUDA 9 and using NCCL2 for CUDA8.

**Comment by alsrgv** [comment]
I'll close this issue as it appears to be resolved.  Feel free to reopen or raise a new one.
