### ISSUE TITLE
undefined symbol: _ZTIN10tensorflow13AsyncOpKernelE

### ISSUE THREAD

**Issue by jianyinglang** [uber/horovod#236]
I did `pip install horovod` after tensorflow build but got the following error message when I tried to load  `horovod.tensorflow`. I used bazel 0.11.1 and gcc6.3 for tensorflow build and openmpi3.0.0 for horovod.

```
>>> import horovod.tensorflow as hvd 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/.tf_17/lib/python3.5/site-packages/horovod/tensorflow/__init__.py", line 41, in <module>
    from horovod.tensorflow.mpi_ops import allgather
  File "$HOME/.tf_17/lib/python3.5/site-packages/horovod/tensorflow/mpi_ops.py", line 56, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "$HOME/.tf_17/lib/python3.5/site-packages/horovod/tensorflow/mpi_ops.py", line 43, in _load_library
    library = load_library.load_op_library(filename)
  File "$HOME/.tf_17/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: $HOME/.tf_17/lib/python3.5/site-packages/horovod/tensorflow/mpi_lib.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTIN10tensorflow13AsyncOpKernelE
```

**Comment by LucaCappelletti94** [comment]
Could you please elaborate further on your solution? Thanks!

**Comment by jianyinglang** [comment]
This problem was caused by different libraries was used between compilation and runtime. My solution was to explicitly set the PATH and LD_LIBRARY_PATH to the correct openmpi library path. One more thing to notice is that when it will download the pre-compiled lib when one uses `pip install horovod`to install. I would recommend using `pip install horovod --no-cache-dir`.
