### ISSUE TITLE
Error when using horovod with tensorflow's slim

### ISSUE THREAD

**Issue by zuowang** [uber/horovod#250]
@alsrgv I modified train_image_classifier.py to use horovod, but I got below errors, could you help me?

```
Traceback (most recent call last):
  File "/examples/models/research/slim/train_horovod.py", line 583, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/examples/models/research/slim/train_horovod.py", line 579, in main
    session_config=sess_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 746, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 1000, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 828, in stop
    ignore_live_threads=ignore_live_threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 989, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 726, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 283, in prepare_session
    init_fn(sess)
  File "/examples/models/research/slim/train_horovod.py", line 322, in callback
    bcast = hvd.broadcast_global_variables(0)
  File "/usr/local/lib/python2.7/dist-packages/horovod/tensorflow/__init__.py", line 93, in broadcast_global_variables
    for var in tf.global_variables()])
  File "/usr/local/lib/python2.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 119, in broadcast
    return MPI_LIB.horovod_broadcast(tensor, name=name, root_rank=root_rank)
  File "<string>", line 94, in horovod_broadcast
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3246, in create_op
    self._check_not_finalized()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2880, in _check_not_finalized
    raise RuntimeError("Graph is finalized and cannot be modified.")
RuntimeError: Graph is finalized and cannot be modified.
```

**Comment by zuowang** [comment]
resolved

**Comment by burness** [comment]
@zuowang  Have you try the multi machine and multi gpus with horovod  ?
