### ISSUE TITLE
use N-1 GPUs for rendering and Nth GPU for training

### ISSUE THREAD

**Issue by ankurhanda** [uber/horovod#262]
Hi Alex, 

I want to know if there is a way to use N-1 GPUs to render the data is a shared buffer that Nth GPU uses for training? I am doing experiments on RL.

**Comment by ankurhanda** [comment]
What I want is something like this https://github.com/uber/horovod/issues/113

**Comment by ankurhanda** [comment]
I tried this
```
hvd.init()
hvd_r=int(hvd.rank())
#each process compute a small part of something and then compute the average etc.
test_array=np.random.rand(hvd.size()*10,100,100)
#compute a small part
x=np.mean(test_array[hvd_r*10:(hvd_r+1)*(10),:,:])
#compute the average for all processes
y=hvd.allreduce(x)
#only one process print out the result
if(hvd_r==0):
    print("mean of the big array is %f"%y)
```
Does hvd not to allreduce on np in tensorflow? I got this error

```
Traceback (most recent call last):
  File "rbd/demo/gym/hvd_test.py", line 11, in <module>
    y=hvd.allreduce(x)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 77, in allreduce
    summed_tensor = _allreduce(tensor)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/mpi_ops.py", line 158, in _allreduce
    name = 'HorovodAllreduce_%s' % _normalize_name(tensor.name)
AttributeError: 'numpy.float64' object has no attribute 'name'
Traceback (most recent call last):
  File "rbd/demo/gym/hvd_test.py", line 11, in <module>
    y=hvd.allreduce(x)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/__init__.py", line 77, in allreduce
    summed_tensor = _allreduce(tensor)
  File "/usr/local/lib/python3.5/dist-packages/horovod/tensorflow/mpi_ops.py", line 158, in _allreduce
    name = 'HorovodAllreduce_%s' % _normalize_name(tensor.name)
AttributeError: 'numpy.float64' object has no attribute 'name'
```

**Comment by alsrgv** [comment]
@ankurhanda, if you're using numpy, you can use `hvd.allreduce()` from `import horovod.keras as hvd`, rather than TensorFlow.

**Comment by ankurhanda** [comment]
```
import tensorflow as tf
import horovod.tensorflow as hvd

def test_horovod_allgather():
    """Test that the allgather correctly gathers 1D, 2D, 3D tensors."""
    hvd.init()
    rank = hvd.rank()
    size = hvd.size()

    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    config.gpu_options.visible_device_list = str(hvd.local_rank())
    
    with tf.Session(config=config) as session:

        tensor = tf.ones([1])* rank
        tensor = tf.cast(tensor, dtype=tf.float32)
        gathered = hvd.allgather(tensor)
        gathered_tensor = session.run(gathered)

        while True:
            print('gathered_tensor = ', gathered_tensor)


test_horovod_allgather()
```

This works for me. Thank you!
