### ISSUE TITLE
Error code -4 when installing horovod

### ISSUE THREAD

**Issue by phil67b** [uber/horovod#306]
Hi. I have an error message when installing horovod.
In bold the text that appears in red in my terminal view.
Maybe someone has an idea. Thanks

root@soap-NM844AA-ABF-m9680fr:~# pip3 install --verbose --no-cache-dir horovod
Created temporary directory: /tmp/pip-ephem-wheel-cache-t3l24w3i
Created temporary directory: /tmp/pip-install-z7vumy6b
Collecting horovod
  1 location(s) to search for versions of horovod:
  * https://pypi.org/simple/horovod/
  Getting page https://pypi.org/simple/horovod/
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/horovod/ HTTP/1.1" 200 2601
  Analyzing links from page https://pypi.org/simple/horovod/
    Found link https://files.pythonhosted.org/packages/8c/91/91495a609f7b4077ba4eeb00c8494bf29eb94de76e5a7a458cf57add7f0e/horovod-0.9.0.tar.gz#sha256=f689e539403ff0b38db114d968437f5223bdbd21d2afe581d6078cc71c4b6b7a (from https://pypi.org/simple/horovod/), version: 0.9.0
    Found link https://files.pythonhosted.org/packages/58/8d/6a84cd3fa9bdeb96e6c162d26d05c6e594c38f788005f2d2f42ed2bfcfe5/horovod-0.9.1.tar.gz#sha256=99608809e2c734507025ffbb4d0f1283983cae542c17484069edd4420e236ccb (from https://pypi.org/simple/horovod/), version: 0.9.1
    Found link https://files.pythonhosted.org/packages/fc/53/314d19c558f726e480489e97d576883b6bd79b7d811913216b30d7849b8b/horovod-0.9.2.tar.gz#sha256=c1c0b5d248e95f1b9c0e269f48cbd8be234fedd02fe56928c79aa8b01d57e0ea (from https://pypi.org/simple/horovod/), version: 0.9.2
    Found link https://files.pythonhosted.org/packages/8a/82/085978898e51938791c35949fb757905e746503369e898074f76f6044d32/horovod-0.9.3.tar.gz#sha256=c252f7e6273c7869f42465f8763840967b0b57794a0dd7e3b525547f216a4481 (from https://pypi.org/simple/horovod/), version: 0.9.3
    Found link https://files.pythonhosted.org/packages/7f/78/3c42b58fa37d5811eb2178e6d8f0e586b18fd883f8575a2da8a7bce9b02b/horovod-0.9.4.tar.gz#sha256=f70cd1fa7138da6201f33e3e91876f61c564dc28b73706fa7aae91967a36fe12 (from https://pypi.org/simple/horovod/), version: 0.9.4
    Found link https://files.pythonhosted.org/packages/07/bb/f2edeee902a6c5e345f5cc6d8ba3f5b6805506489da4bb6cf35665cccd95/horovod-0.9.5.tar.gz#sha256=e61cae1329ba9d052169499e3b008203df44797463df5dee36042333f3b8f647 (from https://pypi.org/simple/horovod/), version: 0.9.5
    Found link https://files.pythonhosted.org/packages/9c/be/5aebe7ecd7024e0ad12196127d22488a73defa3c1b6fac0eea20d7aa6115/horovod-0.9.6.tar.gz#sha256=cbcc9e091659d5954d3283fff85c42e94674e59b8ac5a3e5b40a515bdd1c78df (from https://pypi.org/simple/horovod/), version: 0.9.6
    Found link https://files.pythonhosted.org/packages/9c/62/3d37b3697a06e0c5ef97fd01f690f4b94509486df4f5401a65461e110d1c/horovod-0.9.7.tar.gz#sha256=c5143184be9458085128f817249227602a55ffc9c8994ad8e8af51a158378fd2 (from https://pypi.org/simple/horovod/), version: 0.9.7
    Found link https://files.pythonhosted.org/packages/11/48/e56cb33974a7fc24252e304e7e60b7b892eb7c1093099493913880b6f4ce/horovod-0.9.8.tar.gz#sha256=0cc6d7d1cb2220d432f1c9ecd8cffee2fda7ac2ca970bfad3ad05e6f2b43d0a4 (from https://pypi.org/simple/horovod/), version: 0.9.8
    Found link https://files.pythonhosted.org/packages/2c/c4/cd8d9d1136465e6f23a535cc4c49fad24da92982f1275d7c38a564d5417b/horovod-0.9.9.tar.gz#sha256=9e43d98ce87fe8dbf08131a314cc07bc0330dd656616ecbb689754aadc7cba3e (from https://pypi.org/simple/horovod/), version: 0.9.9
    Found link https://files.pythonhosted.org/packages/b1/83/ac3d9499fdf9173a5870d6fff0a58a4e35240a9c17ce556c3c59cb1a4533/horovod-0.9.10.tar.gz#sha256=37c1e5efdb84fb33c770ca97eca883bd984ed91a84799653005a19ba366759b5 (from https://pypi.org/simple/horovod/), version: 0.9.10
    Found link https://files.pythonhosted.org/packages/81/3b/d4cd7933a1b25dbb6f6a3e4f7e23b1519596c470d2cde5956818f903ac21/horovod-0.9.11.tar.gz#sha256=0ee941d9d9d5ed867ccebaf848239290c43ca10eb5ce153501bf222c1be88250 (from https://pypi.org/simple/horovod/), version: 0.9.11
    Found link https://files.pythonhosted.org/packages/7a/f6/c550b90424136eef13a20527c815778c67d222ec2807e2b526758e5a55f9/horovod-0.9.12.tar.gz#sha256=b418fdc8dff199d1504ab594e0fd155216dce41a4afc99ac0aca8a0025c92181 (from https://pypi.org/simple/horovod/), version: 0.9.12
    Found link https://files.pythonhosted.org/packages/c3/86/c4bab0bccbd5001503e242e7c6b2dd2d4cbef1089775b8008983b410bd73/horovod-0.10.0.tar.gz#sha256=f942525c1a52766ece040679523411588cdcaf26549f7a6e3d2241d02b48981c (from https://pypi.org/simple/horovod/), version: 0.10.0
    Found link https://files.pythonhosted.org/packages/7e/49/5c6b766e2b8071dfce493969332041d1a1210501d44b32f9289f1ecf3b8d/horovod-0.10.1.tar.gz#sha256=541ff099e69bc06a7d019b2a68750afc1984e24f353868a56ca7f6f946d356a8 (from https://pypi.org/simple/horovod/), version: 0.10.1
    Found link https://files.pythonhosted.org/packages/f2/ce/ebc0a4321b3475932543d425f14102fc86ef803be2d1a545ac3297a8e5f4/horovod-0.10.2.tar.gz#sha256=b5e31976d23691e047c1f39609aa6cf1dfbd131f30021c1bc47d3db8a7346cc1 (from https://pypi.org/simple/horovod/), version: 0.10.2
    Found link https://files.pythonhosted.org/packages/d7/83/b1118fc1e2e55394a4b58c293b6a679b047cd46e2559ae9b79e3f2633610/horovod-0.11.0.tar.gz#sha256=f82eebb255a2fb37696c381068cab1b9085c44ba2f30bd43161a4fc45c8423b4 (from https://pypi.org/simple/horovod/), version: 0.11.0
    Found link https://files.pythonhosted.org/packages/6f/88/ad4124c8a0e12ab8b0b32547db6d5477ce21510b09b95d586a927e3427bf/horovod-0.11.1.tar.gz#sha256=25852cde7bf5fc71ba926755d682974641ea0c797df309928e25d04df1038426 (from https://pypi.org/simple/horovod/), version: 0.11.1
    Found link https://files.pythonhosted.org/packages/5c/cd/a5775db7c3e78b255be107089924f2d05293e507266341e3c9e895811b70/horovod-0.11.2.tar.gz#sha256=9bad0fa0accdf7824ceba4620a3ccb0a43ddc51d88875a1c8c140432141dfdbb (from https://pypi.org/simple/horovod/), version: 0.11.2
    Found link https://files.pythonhosted.org/packages/dc/e3/7fd51f21e287ae2cdf21d5a6534e59faf9852a0ef70f43164896c92b44e7/horovod-0.11.3.tar.gz#sha256=b7d748e333e8cccba76a6fc09c92aaad3ffb0f7897d6533443febbf04830e03c (from https://pypi.org/simple/horovod/), version: 0.11.3
    Found link https://files.pythonhosted.org/packages/df/8f/041e0c8f21cacc120ae140a4b9ba62e98cc3519203f6275c063b6b15b6e4/horovod-0.12.0.tar.gz#sha256=1cc6ea5a04594decc455b607f5d1677736c302d8ae58b67711a98a290b47034f (from https://pypi.org/simple/horovod/), version: 0.12.0
    Found link https://files.pythonhosted.org/packages/9c/be/542b5c77897effa83b0a08816bd74ca60b668725801f68d307ca92c9f62b/horovod-0.12.1.tar.gz#sha256=0f09d6bc71ff6dc518c0d9e05a48f9f28d26e6debb21456a5b3be5473c6294f1 (from https://pypi.org/simple/horovod/), version: 0.12.1
    Found link https://files.pythonhosted.org/packages/33/58/133499efe18b1d6e4a5eb76114a1111770e27a845f08fb1e9b2be0bb0be9/horovod-0.13.0.tar.gz#sha256=125f3d795d697c835e564350ec39c013153f1b04303a8ad9844c65b2022cf244 (from https://pypi.org/simple/horovod/), version: 0.13.0
    Found link https://files.pythonhosted.org/packages/46/06/6983c4a20efa0df3c9c662d6913388f1f67a907b89d25b87ed84ae573c05/horovod-0.13.1.tar.gz#sha256=fa2c6532b20b2c8cec4bd997b28e23ddd044fafbd9865e5f842914a418435dcb (from https://pypi.org/simple/horovod/), version: 0.13.1
    Found link https://files.pythonhosted.org/packages/aa/e1/d7f2c04f12bdaaf84dbcb8ada30aaa1f798fb233ae2e9fc1d664589e139e/horovod-0.13.2.tar.gz#sha256=f71b2cb48d4f7b8af0495e4d3fa4aa7887a3198cbf597ae2c16da8069e59490e (from https://pypi.org/simple/horovod/), version: 0.13.2
    Found link https://files.pythonhosted.org/packages/ea/3d/4f36c30798d6feb5e81234693a8e5f4b57e02539603ffb1bc8af47b723b7/horovod-0.13.3.tar.gz#sha256=44bdb955f8dfc36e43698187ecee02be1497a3761c80791f2abe3098601e0212 (from https://pypi.org/simple/horovod/), version: 0.13.3
    Found link https://files.pythonhosted.org/packages/8a/1b/43a2a16e05db68cfbc9eefee0d6af6066eb2a32f512a596371b3f104b48e/horovod-0.13.4.tar.gz#sha256=11baa1d999c0a335f73b602abbe4327223fbdd039816ab34a12f556b04f524fa (from https://pypi.org/simple/horovod/), version: 0.13.4
  Using version 0.13.4 (newest of versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4)
  Created temporary directory: /tmp/pip-unpack-29_9hnbk
  Starting new HTTPS connection (1): files.pythonhosted.org
  https://files.pythonhosted.org:443 "GET /packages/8a/1b/43a2a16e05db68cfbc9eefee0d6af6066eb2a32f512a596371b3f104b48e/horovod-0.13.4.tar.gz HTTP/1.1" 200 93703
  Downloading https://files.pythonhosted.org/packages/8a/1b/43a2a16e05db68cfbc9eefee0d6af6066eb2a32f512a596371b3f104b48e/horovod-0.13.4.tar.gz (93kB)
  Downloading from URL https://files.pythonhosted.org/packages/8a/1b/43a2a16e05db68cfbc9eefee0d6af6066eb2a32f512a596371b3f104b48e/horovod-0.13.4.tar.gz#sha256=11baa1d999c0a335f73b602abbe4327223fbdd039816ab34a12f556b04f524fa (from https://pypi.org/simple/horovod/)
    100% |████████████████████████████████| 102kB 916kB/s 
  Running setup.py (path:/tmp/pip-install-z7vumy6b/horovod/setup.py) egg_info for package horovod
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/horovod.egg-info
    writing top-level names to pip-egg-info/horovod.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/horovod.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/horovod.egg-info/requires.txt
    writing pip-egg-info/horovod.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching '.eggs'
    writing manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-z7vumy6b/horovod has version 0.13.4, which satisfies requirement horovod from https://files.pythonhosted.org/packages/8a/1b/43a2a16e05db68cfbc9eefee0d6af6066eb2a32f512a596371b3f104b48e/horovod-0.13.4.tar.gz#sha256=11baa1d999c0a335f73b602abbe4327223fbdd039816ab34a12f556b04f524fa
Requirement already satisfied: cffi>=1.4.0 in ./.local/lib/python3.5/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in ./.local/lib/python3.5/site-packages (from cffi>=1.4.0->horovod) (2.18)
Installing collected packages: horovod
  Created temporary directory: /tmp/pip-record-56gqd5xo
  Running setup.py install for horovod ...     Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-z7vumy6b/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-56gqd5xo/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.5/horovod
    creating build/lib.linux-x86_64-3.5/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/keras
    creating build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    creating build/lib.linux-x86_64-3.5/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch
    creating build/lib.linux-x86_64-3.5/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.5/horovod/common
    creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.so
error
Cleaning up...
  Removing source in /tmp/pip-install-z7vumy6b/horovod
**Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-z7vumy6b/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-56gqd5xo/install-record.txt --single-version-externally-managed --compile" failed with error code -4 in /tmp/pip-install-z7vumy6b/horovod/**
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-z7vumy6b/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-56gqd5xo/install-record.txt --single-version-externally-managed --compile" failed with error code -4 in /tmp/pip-install-z7vumy6b/horovod/

**Comment by phil67b** [comment]
I resolved the issue.
Finally I did :
- pip install torch
- pip install --verbose --no-cache-dir horovod
