### ISSUE TITLE
Installation Issue with tensorflow 1.9.0rc0

### ISSUE THREAD

**Issue by matthiasreisser** [uber/horovod#311]
I am trying to compile Horovod with the newest tensorflow release (1.9.0rc0). I have compiled the tensorflow wheel myself from the v1.9.0-rc0 branch at 
`git rev-parse HEAD`: `e1436b2952c7600c8ac88114210381db0398be16`

The installation fails with the following error stack: (Paths removed)
`HOROVOD_NCCL_HOME=/HOME/Software/nccl_2.2.13-1+cuda9.0_x86_64/ HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod`

```
HOROVOD_NCCL_HOME=/HOME/Software/nccl_2.2.13-1+cuda9.0_x86_64/ HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod
Collecting horovod
  Downloading https://files.pythonhosted.org/packages/8a/1b/43a2a16e05db68cfbc9eefee0d6af6066eb2a32f512a596371b3f104b48e/horovod-0.13.4.tar.gz (93kB)
    100% |████████████████████████████████| 102kB 12.2MB/s
Requirement already satisfied: cffi>=1.4.0 in /PATHTOVENV/tftemp/lib/python2.7/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in /PATHTOVENV/tftemp/lib/python2.7/site-packages (from cffi>=1.4.0->horovod) (2.18)
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /PATHTOVENV/tftemp/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-eDHffV/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cXZBON/install-record.txt --single-version-externally-managed --compile --install-headers /PATHTOVENV/tftemp/include/site/python2.7/horovod:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
    creating build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/keras
    creating build/lib.linux-x86_64-2.7/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch
    creating build/lib.linux-x86_64-2.7/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-2.7/horovod/common
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    creating build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
    running build_ext
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/HOME/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.so
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/usr/local/cuda/include -I/HOME/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cuda.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cuda.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared build/temp.linux-x86_64-2.7/test_compile/test_cuda.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lcudart -o build/temp.linux-x86_64-2.7/test_compile/test_cuda.so
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/HOME/Software/nccl_2.2.13-1+cuda9.0_x86_64//include -I/usr/local/cuda/include -I/HOME/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_nccl.cc -o build/temp.linux-x86_64-2.7/test_compile/test_nccl.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared build/temp.linux-x86_64-2.7/test_compile/test_nccl.o -L/HOME/Software/nccl_2.2.13-1+cuda9.0_x86_64//lib -L/HOME/Software/nccl_2.2.13-1+cuda9.0_x86_64//lib64 -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lnccl_static -o build/temp.linux-x86_64-2.7/test_compile/test_nccl.so
    building 'horovod.tensorflow.mpi_lib' extension
    creating build/temp.linux-x86_64-2.7/horovod
    creating build/temp.linux-x86_64-2.7/horovod/tensorflow
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/usr/local/cuda/include -I/HOME/Software/nccl_2.2.13-1+cuda9.0_x86_64//include -I/HOME/include/python2.7 -c horovod/tensorflow/mpi_ops.cc -o build/temp.linux-x86_64-2.7/horovod/tensorflow/mpi_ops.o -std=c++11 -fPIC -O2 -I/HOME/include -pthread -Wl,-rpath -Wl,/HOME/lib -Wl,--enable-new-dtags -L/HOME/lib -lmpi -I/PATHTOVENV/tftemp/lib/python2.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /PATHTOVENV/tftemp/lib/python2.7/site-packages/tensorflow/include/tensorflow/stream_executor/dnn.h:33:0,
                     from /PATHTOVENV/tftemp/lib/python2.7/site-packages/tensorflow/include/tensorflow/stream_executor/stream.h:30,
                     from horovod/tensorflow/mpi_ops.cc:29:
    /PATHTOVENV/tftemp/lib/python2.7/site-packages/tensorflow/include/tensorflow/stream_executor/lib/statusor.h:21:46: fatal error: tensorflow/compiler/xla/statusor.h: No such file or directory
     #include "tensorflow/compiler/xla/statusor.h"
                                                  ^
    compilation terminated.
    INFO: Unable to build TensorFlow plugin, will skip it.

    Traceback (most recent call last):
      File "/tmp/pip-install-eDHffV/horovod/setup.py", line 554, in build_extensions
        abi_compile_flags = build_tf_extension(self, options)
      File "/tmp/pip-install-eDHffV/horovod/setup.py", line 421, in build_tf_extension
        build_ext.build_extension(tensorflow_mpi_lib)
      File "/PATHTOVENV/tftemp/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 186, in build_extension
        _build_ext.build_extension(self,ext)
      File "/HOME/lib/python2.7/distutils/command/build_ext.py", line 499, in build_extension
        depends=ext.depends)
      File "/HOME/lib/python2.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/HOME/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
        raise CompileError, msg
    CompileError: command 'gcc' failed with exit status 1

    INFO: Unable to build PyTorch plugin, will skip it.

    Traceback (most recent call last):
      File "/tmp/pip-install-eDHffV/horovod/setup.py", line 565, in build_extensions
        build_torch_extension(self, options, abi_compile_flags)
      File "/tmp/pip-install-eDHffV/horovod/setup.py", line 485, in build_torch_extension
        check_torch_import()
      File "/tmp/pip-install-eDHffV/horovod/setup.py", line 440, in check_torch_import
        'import torch failed, is it installed?\n\n%s' % traceback.format_exc())
    DistutilsPlatformError: import torch failed, is it installed?

    Traceback (most recent call last):
      File "/tmp/pip-install-eDHffV/horovod/setup.py", line 437, in check_torch_import
        import torch
    ImportError: No module named torch


    error: Neither TensorFlow nor PyTorch plugins were built. See errors above.

    ----------------------------------------
Command "/PATHTOVENV/tftemp/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-eDHffV/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cXZBON/install-record.txt --single-version-externally-managed --compile --install-headers /PATHTOVENV/tftemp/include/site/python2.7/horovod" failed with error code 1 in /tmp/pip-install-eDHffV/horovod/ ```

Compiling horovod with my self-built wheel of tensorflow version 1.8.0 works like a charm.

Thanks for your help,

Mat

**Comment by alsrgv** [comment]
Looks like there's an issue in TensorFlow tracker: https://github.com/tensorflow/tensorflow/issues/18841

**Comment by alsrgv** [comment]
The workaround is to copy XLA compiler header files into the python package directory:
```
sudo cp tensorflow/compiler/xla/*.h /usr/local/lib/python3.6/site-packages/tensorflow/include/tensorflow/compiler/xla/
```

I'm following up with the TF team.
