### ISSUE TITLE
install horovod failed on Ubuntu  18.04 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by tingweiwu** [uber/horovod#413]
the reason seems is that : **unable to execute 'x86_64-linux-gnu-gcc': No such file or directory** but i donn't know how to solve this

```shell
root@flashback:~# pip install horovod==0.13.10
Collecting horovod==0.13.10
  Downloading https://files.pythonhosted.org/packages/2c/7e/54f7759bc693ab19480c1b525decab5c1d846cd5fc3af97bda18364a1aa5/horovod-0.13.10.tar.gz (100kB)
    100% |████████████████████████████████| 102kB 101kB/s 
Requirement already satisfied: cffi>=1.4.0 in /usr/local/lib/python3.6/dist-packages (from horovod==0.13.10) (1.11.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi>=1.4.0->horovod==0.13.10) (2.18)
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hp3m7n5r/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_exs66zi/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
    creating build/lib.linux-x86_64-3.6/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
    creating build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    creating build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-Phzf1o/python3.6-3.6.5~rc1=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-Phzf1o/python3.6-3.6.5~rc1=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -stdlib=libc++ -I/usr/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: Unable to determine C++ compilation flags (see error above).
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hp3m7n5r/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_exs66zi/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-hp3m7n5r/horovod/


```

os versionis

```shell
root@flashback:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Bionic Beaver (development branch)"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

**Comment by tgaddair** [comment]
Hey @tingweiwu, it looks like you're missing this `gcc` binary.  Can you try installing some additional packages?

```
sudo apt-get install python-dev gcc
```

**Comment by tingweiwu** [comment]
@tgaddair thanks, I run `apt-get install python-dev gcc` and solved.
now i meet another problem.  seems like `ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory`

I find that `libcublas.so.9.0` is a cuda lib. and  I am installing horovod in docker container(Ubuntu 18.04 LTS )

how should i solve this ? add libcublas.so.9.0 into docker container?

```shell
root@flashback:/# pip install horovod==0.13.10
Collecting horovod==0.13.10
  Using cached https://files.pythonhosted.org/packages/2c/7e/54f7759bc693ab19480c1b525decab5c1d846cd5fc3af97bda18364a1aa5/horovod-0.13.10.tar.gz
Requirement already satisfied: cffi>=1.4.0 in /usr/local/lib/python3.6/dist-packages (from horovod==0.13.10) (1.11.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi>=1.4.0->horovod==0.13.10) (2.18)
Building wheels for collected packages: horovod
  Running setup.py bdist_wheel for horovod ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-5f9ep3kh/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-i3uo1tws --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/horovod
  copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
  creating build/lib.linux-x86_64-3.6/horovod/common
  copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
  creating build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
  creating build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  creating build/lib.linux-x86_64-3.6/horovod/keras
  copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
  copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
  creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
  copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
  creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
  copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
  running build_ext
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
  INFO: Unable to build TensorFlow plugin, will skip it.
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/usr/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 52, in check_tf_version
      import tensorflow as tf
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 22, in <module>
      from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
      from tensorflow.python import pywrap_tensorflow
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
      raise ImportError(msg)
  ImportError: Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/usr/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
  
  
  Failed to load the native TensorFlow runtime.
  
  See https://www.tensorflow.org/install/install_sources#common_installation_problems
  
  for some common reasons and solutions.  Include the entire stack trace
  above this error message when asking for help.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 588, in build_extensions
      abi_compile_flags = build_tf_extension(self, options)
    File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 441, in build_tf_extension
      check_tf_version()
    File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 59, in check_tf_version
      'import tensorflow failed, is it installed?\n\n%s' % traceback.format_exc())
  distutils.errors.DistutilsPlatformError: import tensorflow failed, is it installed?
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/usr/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 52, in check_tf_version
      import tensorflow as tf
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 22, in <module>
      from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
      from tensorflow.python import pywrap_tensorflow
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
      raise ImportError(msg)
  ImportError: Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/usr/lib/python3.6/imp.py", line 243, in load_module
      return load_dynamic(name, filename, file)
    File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
      return _load(spec)
  ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
  
  
  Failed to load the native TensorFlow runtime.
  
  See https://www.tensorflow.org/install/install_sources#common_installation_problems
  
  for some common reasons and solutions.  Include the entire stack trace
  above this error message when asking for help.
  
  
  INFO: Unable to build PyTorch plugin, will skip it.
  
  Traceback (most recent call last):
    File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 471, in check_torch_import
      import torch
  ModuleNotFoundError: No module named 'torch'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 599, in build_extensions
      build_torch_extension(self, options, abi_compile_flags)
    File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 519, in build_torch_extension
      check_torch_import()
    File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 474, in check_torch_import
      'import torch failed, is it installed?\n\n%s' % traceback.format_exc())
  distutils.errors.DistutilsPlatformError: import torch failed, is it installed?
  
  Traceback (most recent call last):
    File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 471, in check_torch_import
      import torch
  ModuleNotFoundError: No module named 'torch'
  
  
  error: Neither TensorFlow nor PyTorch plugins were built. See errors above.
  
  ----------------------------------------
  Failed building wheel for horovod
  Running setup.py clean for horovod
Failed to build horovod
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-5f9ep3kh/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cm8k7iyn/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
    creating build/lib.linux-x86_64-3.6/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
    creating build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    creating build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
    INFO: Unable to build TensorFlow plugin, will skip it.
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/usr/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 52, in check_tf_version
        import tensorflow as tf
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 22, in <module>
        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/usr/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
    
    
    Failed to load the native TensorFlow runtime.
    
    See https://www.tensorflow.org/install/install_sources#common_installation_problems
    
    for some common reasons and solutions.  Include the entire stack trace
    above this error message when asking for help.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 588, in build_extensions
        abi_compile_flags = build_tf_extension(self, options)
      File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 441, in build_tf_extension
        check_tf_version()
      File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 59, in check_tf_version
        'import tensorflow failed, is it installed?\n\n%s' % traceback.format_exc())
    distutils.errors.DistutilsPlatformError: import tensorflow failed, is it installed?
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/usr/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 52, in check_tf_version
        import tensorflow as tf
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 22, in <module>
        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/usr/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
    
    
    Failed to load the native TensorFlow runtime.
    
    See https://www.tensorflow.org/install/install_sources#common_installation_problems
    
    for some common reasons and solutions.  Include the entire stack trace
    above this error message when asking for help.
    
    
    INFO: Unable to build PyTorch plugin, will skip it.
    
    Traceback (most recent call last):
      File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 471, in check_torch_import
        import torch
    ModuleNotFoundError: No module named 'torch'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 599, in build_extensions
        build_torch_extension(self, options, abi_compile_flags)
      File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 519, in build_torch_extension
        check_torch_import()
      File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 474, in check_torch_import
        'import torch failed, is it installed?\n\n%s' % traceback.format_exc())
    distutils.errors.DistutilsPlatformError: import torch failed, is it installed?
    
    Traceback (most recent call last):
      File "/tmp/pip-install-5f9ep3kh/horovod/setup.py", line 471, in check_torch_import
        import torch
    ModuleNotFoundError: No module named 'torch'
    
    
    error: Neither TensorFlow nor PyTorch plugins were built. See errors above.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-5f9ep3kh/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cm8k7iyn/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-5f9ep3kh/horovod/
root@flashback:/# 

```

**Comment by pymia** [comment]
Yes, from my experience installed horovod in Ubuntu 18.04, and run successfully.

Make sure nvidia driver, cuda and cuDNN, and configure the CUDA and cuDNN library paths.
After that, install Open MPI and horovod afterwards.

if you have no idea about the CUDA and cuDNN part, use the bellowing link, it works on Ubuntu 18.04 as well.

https://medium.com/@zhanwenchen/install-cuda-and-cudnn-for-tensorflow-gpu-on-ubuntu-79306e4ac04e

**Comment by tgaddair** [comment]
It looks like you need to install Tensorflow with GPU support.  I'd suggest taking a look at their docs and let me know if that works for you:

https://www.tensorflow.org/install/install_linux#NVIDIARequirements

**Comment by tingweiwu** [comment]
@pymia after I install nvidia driver, cuda and cuDNN on my container.   and horovod installed successfully

**Comment by tingweiwu** [comment]
@tgaddair I  have installed tensorflow-gpu in a container. and my nvidia driver, cuda and cuDNN are installed on host, so i installed horovod failed . after i add cuda and cuDNN installed in container. horovod  installed success

**Comment by pymia** [comment]
@tingweiwu that's great!
