### ISSUE TITLE
Horovod :Running on multiple machines

### ISSUE THREAD

**Issue by hamzafar** [uber/horovod#415]
Hi,

I am trying to configuring horvod on three ubuntu 16.04 machines (i7 processor with geforce 1070 card). Although, I have successfully configured each of the machine and horovod example given below, is successfully working on each of the node:(Running on a single machine)
`nvidia-docker run -it horovod:latest
root@c278c88dd552:/examples# mpirun -np 4 -H localhost:4 python keras_mnist_advanced.py`

However, I can't able to run the following command on machine(Running on multiple machines):

`sudo nvidia-docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest root@c278c88dd552:/examples# mpirun -np 3 -H host1:1,host2:1,host3:1 \
    -mca plm_rsh_args "-p 12345" python keras_mnist_advanced.py`

and having following error: 
![hv-dst](https://user-images.githubusercontent.com/6842017/43524524-92711d7c-95b0-11e8-9e71-2c5ef6e64aaf.png)

I have also configured password less login with each three machine recommended by the [link](http://www.linuxproblem.org/art_9.html)

I am newbie to ubuntu, and I believe I am not able to understand the ` /mnt/share/ssh` in the distributed code. 
It would be great if anyone can help me out to work the code.

Regards
Hamza Zafar

**Comment by tgaddair** [comment]
Hey @hamzafar, it looks like you're attempting to run the example [here](https://github.com/uber/horovod/blob/master/docs/docker.md) here verbatim as one big command line.

The actual command you want to run is:

```
nvidia-docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest
```

This will place you in a new shell within your docker process.  From here, you can run the command to start the training:

```
mpirun -np 3 -H host1:1,host2:1,host3:1 -mca plm_rsh_args "-p 12345" python keras_mnist_advanced.py
```

The `root@c278c88dd552:/examples#` is just to illustrate an example of what your prompt will look like, similar to how your is `aifi@c1:~h-script$` in the image above.  Does that make sense?

Let me know if that helps.

**Comment by hamzafar** [comment]
Hi @tgaddair, Thank you for recommending me solution for running horovod. I am running horovod on single machine using the following command:
` nvidia-docker run -it horovod:latest
root@c278c88dd552:/examples# mpirun -np 4 -H localhost:4 python keras_mnist_advanced.py`

But I can't do learning in the distributed environment. 

For the sake of simplicity, I am using only two machines with the static ip's 192.168.10.235 and 192.168.10.236 respectively. The both systems can do passwordless ssh in the terminal in ubuntu level as well as docker container.

Whenever, I execute distributed hovorod command on two machines, the system sleeps unlimited time and does not provide output. 

Although, I have tried multiple solutions to run horovod on distributed systems, but still no luck. The following is configuration of my machines:

- Each machine is running on ubuntu 16.04, with core i7 processor and Geforce GTX 1070 Gpu.

Now, What I need to show all my approaches to an expert  and that can give me recommendations to run it distributed environment. 

Regards
Hamza Zafar

**Comment by alsrgv** [comment]
@hamzafar, as @tgaddair mentioned, you should NOT have `root@c278c88dd552:/examples#` in your command.  Can you remove it and try again?  If it does not work, please share the output.

**Comment by hamzafar** [comment]
@tgaddair, Thank you for recommendation, I am pleased to share that I have resolved the error you have mentioned above.

But about couple of days, I am helpless to run horovod on distributed machines. Like I have two machine  s on which I am trying to excuted keras_advanced_minst.py in distributed manner. But, every time I ran 
the script I got error:

`bash: /usr/local/bin/orted: No such file or directory`
Although I am sucessully ssh from docker to other docker, but don't know how I can reslove this issue. 

I have also attached the screen shot of two machine, where one machine is working as secondary and other is working as primary. In primary machine I have ssh to secondary, and then returned to primary machine. 
I have also invoked the distributed job in the screen shot at the botom, and it showed  `bash: /usr/local/bin/orted: No such file or directory`

Please find the attached screen shot, and recommend me the error that I can resolve to run horovod distributed.

![orted_error](https://user-images.githubusercontent.com/6842017/43999440-652d4a46-9e1d-11e8-9404-489ba7983dec.png)
Regards
Hamza Zafar

**Comment by alsrgv** [comment]
@hamzafar, can you remove `aifi@` from your command, align port #s (you need to use 2222 on both sides):
```
$ mpirun -np 2 -H m1:1,m2:1 -mca pml_rsh_args "-p 2222" python keras_mnist_advanced.py
```

**Comment by hamzafar** [comment]
@alsrgv, I have made consistency in ports on both machine i.e. they both are running on port 12345, but when I invoke mpi job in primary machine (m1) as:

`mpirun -np 2 -H m1:1,m2:1 -mca plm_rsh_args "-p 12345 -v" python keras_mnist_advanced.py`

It ended up with some hang, you can see the screen shot of the hang as below:
![err-1](https://user-images.githubusercontent.com/6842017/44094622-bc950abe-9fe7-11e8-85ac-cd5d8b80e654.png)

Following [hangs-due-to-non-routed-network-interfaces](https://github.com/uber/horovod/blob/master/docs/running.md#hangs-due-to-non-routed-network-interfaces)

I found out docker0, enp6s0, enp4s0, lo on both primary and secondary machines as:
![ifconfig](https://user-images.githubusercontent.com/6842017/44094860-57f5e064-9fe8-11e8-9c50-cfe78c357eda.png)

Then, I executed mpi job as follows:
`mpirun -np 2 -H m1:1,m2:1 -mca plm_rsh_args "-p 12345 -v" -mca btl_tcp_if_exclude docker0,enp6s0,enp4s0,lo -x NCCL_SOCKET_IFNAME=^docker0,enp6s0,enp4s0,lo python keras_mnist_advanced.py`

But had no luck to run distributed job, the error was same:
![err-2](https://user-images.githubusercontent.com/6842017/44095027-ce933406-9fe8-11e8-87aa-e1b1da6b3c2b.png)
(PS: **In screenshot, I have not use python before `keras_mnist_advanced.py`, but when I included `python keras_mnist_advanced.py` it returned me same issue**)

Following the kernel [docker distributed sample cannot work #162](https://github.com/uber/horovod/issues/162) and excuting ssh commands from root:
`root@m1:/examples# ssh -p 12345 -v m2 ` 

resulted in some error as :
`debug1: Next authentication method: password`
`root@m2's password:` 
`debug1: Authentications that can continue: publickey,password`
`Permission denied, please try again.`
`root@m2's password:` 
`debug1: Authentications that can continue: publickey,password`
`Permission denied, please try again.`
`root@m2's password:` 
`debug1: Authentications that can continue: publickey,password`
`debug1: No more authentication methods to try.`
`Permission denied (publickey,password).`

I can't figure out how to resolve this, but if this error is due to ssh configuration, it would be highly appreciated if you can provide detail instruction how we can configure ssh passwordless other than [Recommended link in horovod configuration](http://www.linuxproblem.org/art_9.html).

**Comment by lpinilla** [comment]
Can confirm, had the same problem and creating the priv/pub keys and the authorized_keys file from root user fixed my problem

**Comment by abditag2** [comment]
In order for horovod to work, the driver needs to be able to ssh into all the workers and all the workers need to be able to ssh into each other (this is a superset of the actual condition in the ring) without any password prompts. So pub private keys and list of authorized_keys must have been configured properly.

**Comment by lpinilla** [comment]
I understand the need but on the [instructions](https://github.com/horovod/horovod/blob/master/docs/docker.rst), there isn't step for the master to listen for ssh on specific ports (like they do with the slaves using /usr/sbin/sshd -p 12345) so, when the slave machine ssh's to the master, wouldn't it be connecting to the host machine because of the --network=host flag?

**Comment by arnab44** [comment]
Hi,
I'm trying to run horovod in multiple host but not sucessful.

Below is what I'm doing . Secondary host:

$ nvidia-docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest \
    bash -c "/usr/sbin/sshd -p 12345; sleep infinity"

In primary host:

$nvidia-docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest      

root@ip-172-31-56-64:/examples#  horovodrun -np 2 -H localhost:1,3.89.39.190:1 -p 12345 --verbose python train.py 

```
Filtering local host names.
Remote host found: 3.89.39.190
Checking ssh on all remote hosts.
ssh not successful for host 3.89.39.190:
ssh: connect to host 3.89.39.190 port 12345: Connection timed out

Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 768, in run_commandline
    _run(args)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 758, in _run
    return _run_static(args)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 586, in _run_static
    raise RuntimeError('could not connect to some hosts via ssh')
RuntimeError: could not connect to some hosts via ssh
```


Above is the error I'm getting
 I have set password less authentication for both the host and can log into both host from each other without giving and key or password. I can also ssh into the hosts from each other from inside the horovod docker container.

Please help how can I solve this issue.

**Comment by hamzafar** [comment]
Hi @arnab44,

I will recommend you to make sure the ssh communication between the servers should be at root level.

**Comment by arnab44** [comment]
@hamzafar  Thanks for reply. I checked, it's working for root level ssh as well.

**Comment by siddhantsahu** [comment]
@arnab44 did you get that to work finally? I'm facing the same issue.
