### ISSUE TITLE
Failed to install horovod on Ubuntu 18.04

### ISSUE THREAD

**Issue by zelinlv** [uber/horovod#417]
```
pip install Horovod
Collecting Horovod
  Using cached https://files.pythonhosted.org/packages/cd/7d/8fc395fe9b2b3d4f769d3a778c6991fdd8c8f998df79b4967b4df5f8ec0d/horovod-0.13.11.tar.gz
Collecting cffi>=1.4.0 (from Horovod)
  Using cached https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.4.0->Horovod)
Building wheels for collected packages: Horovod
  Running setup.py bdist_wheel for Horovod ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2Cfqnx/Horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpzoHA3Ppip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/horovod
  copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
  creating build/lib.linux-x86_64-2.7/horovod/torch
  copying horovod/torch/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch
  copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/torch
  creating build/lib.linux-x86_64-2.7/horovod/common
  copying horovod/common/__init__.py -> build/lib.linux-x86_64-2.7/horovod/common
  creating build/lib.linux-x86_64-2.7/horovod/tensorflow
  copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
  creating build/lib.linux-x86_64-2.7/horovod/keras
  copying horovod/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/keras
  copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/keras
  creating build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
  copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
  creating build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib
  copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib
  running build_ext
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.so
  error: mpicxx -show failed (see error below), is MPI in $PATH?
  Note: If your version of MPI has a custom command to show compilation flags, please specify it with the HOROVOD_MPICXX_SHOW environment variable.
  
  Traceback (most recent call last):
    File "/tmp/pip-build-2Cfqnx/Horovod/setup.py", line 194, in get_mpi_flags
      shlex.split(show_command), universal_newlines=True).strip()
    File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
      process = Popen(stdout=PIPE, *popenargs, **kwargs)
    File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
      errread, errwrite)
    File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
      raise child_exception
  OSError: [Errno 2] No such file or directory
  
  
  ----------------------------------------
  Failed building wheel for Horovod
  Running setup.py clean for Horovod
Failed to build Horovod
Installing collected packages: pycparser, cffi, Horovod
  Running setup.py install for Horovod ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2Cfqnx/Horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1iBnfo-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
    creating build/lib.linux-x86_64-2.7/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/torch
    creating build/lib.linux-x86_64-2.7/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-2.7/horovod/common
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    creating build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/keras
    creating build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.so
    error: mpicxx -show failed (see error below), is MPI in $PATH?
    Note: If your version of MPI has a custom command to show compilation flags, please specify it with the HOROVOD_MPICXX_SHOW environment variable.
    
    Traceback (most recent call last):
      File "/tmp/pip-build-2Cfqnx/Horovod/setup.py", line 194, in get_mpi_flags
        shlex.split(show_command), universal_newlines=True).strip()
      File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2Cfqnx/Horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1iBnfo-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-2Cfqnx/Horovod/
```
I think I have already installed open MPI by following the instruction posted on the README file of horovod. Help please

**Comment by zelinlv** [comment]
@alsrgv thanks for replying! I reinstalled the environment and it worked.
