### ISSUE TITLE
Unable to install Horovod on CENTOS 7.5

### ISSUE THREAD

**Issue by rajchinna** [uber/horovod#448]
running install
running bdist_egg
running egg_info
writing requirements to horovod.egg-info/requires.txt
writing horovod.egg-info/PKG-INFO
writing top-level names to horovod.egg-info/top_level.txt
writing dependency_links to horovod.egg-info/dependency_links.txt
reading manifest file 'horovod.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '.eggs'
writing manifest file 'horovod.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-2.7/horovod/torch/test_cuda
copying horovod/torch/test_cuda/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/test_cuda
running build_ext
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o -L/usr/lib64 -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.so
building 'horovod.tensorflow.mpi_lib' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c horovod/tensorflow/mpi_ops.cc -o build/temp.linux-x86_64-2.7/horovod/tensorflow/mpi_ops.o -std=c++11 -fPIC -O2 -I/usr/include/openmpi-i386 -pthread -m32 -Wl,-rpath -Wl,/usr/lib/openmpi/lib -Wl,--enable-new-dtags -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -I/root/envs/exp/lib/python2.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1
In file included from /platform/include/c++/6.3.0/random:49:0,
                 from /root/envs/exp/lib/python2.7/site-packages/tensorflow/include/unsupported/Eigen/CXX11/Tensor:63,
                 from /root/envs/exp/lib/python2.7/site-packages/tensorflow/include/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from /root/envs/exp/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/numeric_types.h:20,
                 from /root/envs/exp/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/allocator.h:23,
                 from /root/envs/exp/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:23,
                 from horovod/tensorflow/mpi_ops.cc:23:
/platform/include/c++/6.3.0/bits/random.h:107:26: error: expected unqualified-id before ‘__int128’
       { typedef unsigned __int128 type; };
                          ^~~~~~~~
INFO: Unable to build TensorFlow plugin, will skip it.

Traceback (most recent call last):
  File "setup.py", line 625, in build_extensions
    abi_compile_flags = build_tf_extension(self, options)
  File "setup.py", line 465, in build_tf_extension
    build_ext.build_extension(tensorflow_mpi_lib)
  File "/root/envs/exp/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 498, in build_extension
    depends=ext.depends)
  File "/usr/lib64/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python2.7/distutils/unixccompiler.py", line 132, in _compile
    raise CompileError, msg
CompileError: command 'gcc' failed with exit status 1

generating /tmp/tmpPPdVhJ/_test_cuda.c
setting the current directory to '/tmp/tmpPPdVhJ'
running build_ext
building '_test_cuda' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/root/envs/exp/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/root/envs/exp/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/root/envs/exp/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/include/python2.7 -c _test_cuda.c -o ./_test_cuda.o -std=c99 -std=c11 -fPIC -O2
In file included from /root/envs/exp/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _test_cuda.c:493:
/root/envs/exp/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
INFO: Above error indicates that this PyTorch installation does not support CUDA.
generating build/horovod/torch/mpi_lib/_mpi_lib.c
(already up-to-date)
not modified: 'build/horovod/torch/mpi_lib/_mpi_lib.c'
generating build/horovod/torch/mpi_lib_impl/_mpi_lib_impl.cc
(already up-to-date)
not modified: 'build/horovod/torch/mpi_lib_impl/_mpi_lib_impl.cc'
building 'horovod.torch.mpi_lib_impl._mpi_lib_impl' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_CUDA=0 -DTORCH_VERSION=4001000 -I/root/envs/exp/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/root/envs/exp/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/include/python2.7 -c build/horovod/torch/mpi_lib_impl/_mpi_lib_impl.cc -o build/temp.linux-x86_64-2.7/build/horovod/torch/mpi_lib_impl/_mpi_lib_impl.o -std=c99 -std=c++11 -fPIC -O2 -I/usr/include/openmpi-i386 -pthread -m32 -Wl,-rpath -Wl,/usr/lib/openmpi/lib -Wl,--enable-new-dtags -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi
cc1plus: warning: command line option ‘-std=c99’ is valid for C/ObjC but not for C++
In file included from build/horovod/torch/mpi_lib_impl/_mpi_lib_impl.cc:22:0:
/usr/include/python2.7/pyconfig.h:4:25: fatal error: pyconfig-32.h: No such file or directory
 #include "pyconfig-32.h"
                         ^
compilation terminated.
INFO: Unable to build PyTorch plugin, will skip it.

Traceback (most recent call last):
  File "setup.py", line 636, in build_extensions
    build_torch_extension(self, options, abi_compile_flags)
  File "setup.py", line 611, in build_torch_extension
    build_ext.build_extension(setuptools_ext)
  File "/root/envs/exp/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 498, in build_extension
    depends=ext.depends)
  File "/usr/lib64/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python2.7/distutils/unixccompiler.py", line 132, in _compile
    raise CompileError, msg
CompileError: command 'gcc' failed with exit status 1

error: Neither TensorFlow nor PyTorch plugins were built. See errors above.

**Comment by tgaddair** [comment]
Hey @rajchinna, looks like an environment issue.  Could you try taking a look at [this](https://github.com/locuslab/pytorch_fft/issues/21) issue, and #383 and see if any of those suggestions work for you?

**Comment by Approximetal** [comment]
> Hey @rajchinna, looks like an environment issue. Could you try taking a look at [this](https://github.com/locuslab/pytorch_fft/issues/21) issue, and #383 and see if any of those suggestions work for you?

Hi @tgaddair, I met the same problem, I use this command to install horovod which indicate the path of cuda: `HOROVOD_NCCL_INCLUDE=/usr/include HOROVOD_NCCL_LIB=/usr/lib64 HOROVOD_CUDA_HOME=/usr/local/cuda-9.2 HOROVOD_CUDA_INCLUDE=/usr/local/cuda-9.2/include HOROVOD_WITH_PYTORCH=1 HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_CPU_OPERATIONS=MPI HOROVOD_WITH_MPI=1 HOROVOD_WITHOUT_GLOO=1 pip install --no-cache-dir horovod`

but it still occurs: 

```
......
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  In file included from /home/zhiyuan.zhao/anaconda3/envs/horovod/lib/python3.6/site-packages/torch/include/THC/THCGeneral.h:7:0,
                   from /home/zhiyuan.zhao/anaconda3/envs/horovod/lib/python3.6/site-packages/torch/include/THC/THC.h:4,
                   from build/temp.linux-x86_64-3.6/test_compile/test_torch_cuda.cc:1:
  /home/zhiyuan.zhao/anaconda3/envs/horovod/lib/python3.6/site-packages/torch/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory
   #include <cuda_runtime_api.h>
            ^~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  INFO: Above error indicates that this PyTorch installation does not support CUDA.
```
