### ISSUE TITLE
Tensorflow visible_device_list GPU id larger than visible device count

### ISSUE THREAD

**Issue by zhimengfan1990** [uber/horovod#520]
I'm running a keras/tensorflow program on two DGX-1(each with 8 GPUs). But I got an error that says I don't have more than 8 GPUs. Log is below: 
```
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
--------------------------------------------------------------------------
Two mutually-exclusive MCA variables were specified.  This can result
in undefined behavior, such as ignoring the components that the MCA
variables are supposed to affect.

  1st MCA variable: btl_tcp_if_include
    Source of value: environment
  2nd MCA variable: btl_tcp_if_exclude
    Source of value: file (/usr/local/etc/openmpi-mca-params.conf:61)
--------------------------------------------------------------------------
2018-09-26 05:24:26.267263: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267333: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267492: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267638: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267626: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267654: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267683: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267757: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267746: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267832: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267842: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.267926: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.268050: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.268198: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.268232: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:26.268257: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-26 05:24:28.797251: E tensorflow/core/common_runtime/direct_session.cc:154] Invalid argument: 'visible_device_list' listed an invalid GPU id '13' but visible device count is 8
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./scripts/train.py", line 43, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1560, in __init__
2018-09-26 05:24:28.797720: E tensorflow/core/common_runtime/direct_session.cc:154] Invalid argument: 'visible_device_list' listed an invalid GPU id '14' but visible device count is 8
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 633, in __init__
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    self._session = tf_session.TF_NewSession(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./scripts/train.py", line 43, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1560, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 633, in __init__

```

**Comment by tgaddair** [comment]
Hey @zhimengfan1990, could you share your `mpirun` command and the output of `nvidia-smi`?

Also, if you have `CUDA_VISIBLE_DEVICES` set anywhere, could you try unsetting it (see #94)?

**Comment by zhimengfan1990** [comment]
Hi @tgaddair , my command is `mpirun -np 16  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH  python my_script.py`, inside docker. We are using DGX clusters, and no admin privilege, we can't use `nvidia-smi`

**Comment by tgaddair** [comment]
Thanks @zhimengfan1990, and can you verify that `CUDA_VISIBLE_DEVICES` is unset?

Also, could you try running with `-bind-to none -map-by slot`?

**Comment by zhimengfan1990** [comment]
Hi @tgaddair , Yes I tried to add `-bind-to none -map-by slot`, still got the same error...

**Comment by alsrgv** [comment]
@zhimengfan1990, the service should have a way to provide you names/IPs of nodes that are part of the job that you're running.  Cluster admins should be able to point you to the right way of getting this information.

**Comment by zhimengfan1990** [comment]
@alsrgv  Yes, that's reasonable. I'll check with the admin of the cluster. Thanks!

**Comment by zhimengfan1990** [comment]
Fixed it now, the file in docker image `/usr/local/etc/openmpi-mca-params.conf` is conflict with our cluster configuration. After removing it in docker image, it can run on our cluster.

**Comment by shaunstoltz** [comment]
This seems to be a wide spread problem, have tried on two machines, and just keep on getting this error when trying accross more than one machine.

**Comment by ssstuvz** [comment]
> @zhimengfan1990, since you're running on multiple machines, you should use `-H server1:8,server2:8` in addition to specifying the number of processes. Since you don't specify `-H`, MPI will run all 16 processes on a single server. It's a good idea to add other flags from https://github.com/uber/horovod/blob/master/docs/running.md as well.

I am really wondering whether -H flag is needed when using SLURM. It definitely works fine without this flag on a single node!
