### ISSUE TITLE
AssertionError: Local gradient accumulation

### ISSUE THREAD

**Issue by andfoy** [uber/horovod#543]
Hi,
I'm trying to implement gradient accumulation as described on this [PyTorch discussion thread](https://discuss.pytorch.org/t/how-to-implement-accumulated-gradient/3822/8?u=andfoy) to train a large model by breaking down a larger input batch into smaller batches, accumulating the resulting gradients and then updating the optimizer. 

```python
partial_loss = 0
start_time = time.time()
iter_size = math.ceil(candidates.size(0) / args.num_candidates)
for i in range(0, candidates.size(0), args.num_candidates):
    candidates_x = candidates[i: i + args.num_candidates]
    labels_x = labels[i: i + args.num_candidates]
    candidates_x = candidates_x.to(device)
    labels_x = labels_x.to(device)
    scores = net(img, phrase, candidates_x)
    loss = criterion(scores, labels_x) / iter_size
    partial_loss += loss
    loss.backward()
optimizer.step()
```

While this approach works on a single GPU, it fails when using Horovod, as it displays the following error stacktrace. We've also experienced this error before when trying to train GANs in a distributed manner, also using Horovod.

```python 
bcv005:3290:3535 [0] NCCL INFO NET : Using interface eno1:157.253.243.11<0>
bcv005:3290:3535 [0] NCCL INFO NET/IB : Using interface eno1 for sideband communication
bcv005:3290:3535 [0] NCCL INFO Using internal Network Socket
bcv005:3290:3535 [0] NCCL INFO NET : Using interface eno1:157.253.243.11<0>
bcv005:3290:3535 [0] NCCL INFO NET : Using interface ztbto2ybf2:10.241.99.233<0>
bcv005:3290:3535 [0] NCCL INFO NET : Using interface br-515dfe9b9b35:172.18.0.1<0>
bcv005:3290:3535 [0] NCCL INFO NET : Using interface br-e84ee09ce056:172.19.0.1<0>
bcv005:3290:3535 [0] NCCL INFO NET/Socket : 4 interfaces found
NCCL version 2.3.5+cuda9.0
bcv005:3290:3535 [0] NCCL INFO rank 0 nranks 2
bcv005:3291:3534 [1] NCCL INFO NET : Using interface eno1:157.253.243.11<0>
bcv005:3291:3534 [1] NCCL INFO NET/IB : Using interface eno1 for sideband communication
bcv005:3291:3534 [1] NCCL INFO Using internal Network Socket
bcv005:3291:3534 [1] NCCL INFO rank 1 nranks 2
bcv005:3290:3535 [0] NCCL INFO comm 0x7f5308380cd0 rank 0 nranks 2
bcv005:3290:3535 [0] NCCL INFO Could not find real path of /sys/class/net/ztbto2ybf2/device
bcv005:3290:3535 [0] NCCL INFO Could not find real path of /sys/class/net/br-515dfe9b9b35/device
bcv005:3290:3535 [0] NCCL INFO Could not find real path of /sys/class/net/br-e84ee09ce056/device
bcv005:3290:3535 [0] NCCL INFO CUDA Dev 0, IP Interfaces : eno1(SOC) ztbto2ybf2(SOC) br-515dfe9b9b35(SOC) br-e84ee09ce056(SOC) 
Traceback (most recent call last):
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/SSD3/score-textseg/ref_score_net/train.py", line 483, in <module>
    train_loss = train(epoch)
  File "/media/SSD3/score-textseg/ref_score_net/train.py", line 359, in train
    loss.backward()
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/horovod/torch/__init__.py", line 77, in hook
    assert p not in self._handles
AssertionError
bcv005:3291:3534 [1] NCCL INFO comm 0x7fb190371510 rank 1 nranks 2
bcv005:3291:3534 [1] NCCL INFO NET : Using interface eno1:157.253.243.11<0>
bcv005:3291:3534 [1] NCCL INFO NET : Using interface ztbto2ybf2:10.241.99.233<0>
bcv005:3291:3534 [1] NCCL INFO NET : Using interface br-515dfe9b9b35:172.18.0.1<0>
bcv005:3291:3534 [1] NCCL INFO NET : Using interface br-e84ee09ce056:172.19.0.1<0>
bcv005:3291:3534 [1] NCCL INFO NET/Socket : 4 interfaces found
bcv005:3291:3534 [1] NCCL INFO Could not find real path of /sys/class/net/ztbto2ybf2/device
bcv005:3291:3534 [1] NCCL INFO Could not find real path of /sys/class/net/br-515dfe9b9b35/device
bcv005:3291:3534 [1] NCCL INFO Could not find real path of /sys/class/net/br-e84ee09ce056/device
bcv005:3291:3534 [1] NCCL INFO CUDA Dev 1, IP Interfaces : eno1(SOC) ztbto2ybf2(SOC) br-515dfe9b9b35(SOC) br-e84ee09ce056(SOC) 
bcv005:3290:3535 [0] NCCL INFO Using 256 threads
bcv005:3290:3535 [0] NCCL INFO Min Comp Cap 6
bcv005:3290:3535 [0] NCCL INFO Ring 00 :    0   1
bcv005:3290:3535 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC
bcv005:3291:3534 [1] NCCL INFO Ring 00 : 1[1] -> 0[0] via P2P/IPC
bcv005:3290:3535 [0] NCCL INFO Launch mode Parallel
Traceback (most recent call last):
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/SSD3/score-textseg/ref_score_net/train.py", line 483, in <module>
    train_loss = train(epoch)
  File "/media/SSD3/score-textseg/ref_score_net/train.py", line 359, in train
    loss.backward()
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/horovod/torch/__init__.py", line 77, in hook
    assert p not in self._handles
AssertionError
```

I would like to know if it is possible to perform local gradient accumulation on a single GPU, and then all-reduce it on the other ones.

**Comment by andfoy** [comment]
After taking a look at https://github.com/uber/horovod/blob/master/horovod/torch/__init__.py#L75, I thought if its possible to introduce a new ``_DistributedOptimizer._deregister_hooks``, which would disable all the all_reduce operations that could happen after performing a ``.backward()`` call. By doing so, I think the code example would look like this:

```python
partial_loss = 0
start_time = time.time()
optimizer._deregister_hooks()
iter_size = math.ceil(candidates.size(0) / args.num_candidates)
for i in range(0, candidates.size(0), args.num_candidates):
    candidates_x = candidates[i: i + args.num_candidates]
    labels_x = labels[i: i + args.num_candidates]
    candidates_x = candidates_x.to(device)
    labels_x = labels_x.to(device)
    scores = net(img, phrase, candidates_x)
    loss = criterion(scores, labels_x) / iter_size
    partial_loss += loss
    if (i + args.num_candidates) >= candidates.size(0):
        optimizer._register_hooks()
    loss.backward()
optimizer.step()
```
By temporarily disabling the backward hooks that are used to perform the all_reduce operation, it should be possible to accumulate the gradient locally, which then is synchronized on the last iteration by enabling the hooks once again? Is this idea wrong?

**Comment by alsrgv** [comment]
@andfoy, I believe this is very similar to #455.  A contribution like this would be very welcome.  There are few enhancements I'd suggest:
1. Name method something like `ignore_gradients(True/False)`
2. In assertion, failure should suggest this scenario and using `ignore_gradients()`
3. `ignore_gradients()` should still remember parameters, but not invoke allreduce.  Then, if the user forgets to un-ignore gradients on the last iteration, `synchronize()` would perform allreduce and print a one-time warning.

**Comment by andfoy** [comment]
@alsrgv Thanks for the feedback, I'll introduce your suggested changes, and send a PR for further discussion
