### ISSUE TITLE
horovod allreduce often crashs while saving last step

### ISSUE THREAD

**Issue by LiweiPeng** [uber/horovod#575]
I am using latest tensorflow 1.11.0 + horovod code (master branch as of 10/19/2018) to run distributed transformer training. Often (but not always) the last saving checkpoint crashed at gradient allreduce. 

i am using 10 GPUs for my test. When it works normally, all 10 processes will print out 'Loss for final step xxx'. When it crashes, only 1 process print out 'Loss for final step xxx', all other 9 processes got the shutown error and crashed with shutdown err.

I use tf.data.TextLineDataset(src_file).shard(hvd.size(), hvd.rank()) to shard the dataset. One possible reason is that different process gets different size of data. such that one process stops at its last step while others still have data to train.

**The question is:  how can i avoid this?**

**some crash exception stack**

  File "/home/liwei.peng/work/alitranx/hvd/transformer.py", line 604, in transformer_model_fn
    grad = hvd_allreduce(grads_and_vars)
  File "/home/liwei.peng/work/alitranx/hvd/transformer.py", line 646, in hvd_allreduce
    avg_grad = hvd.allreduce(grad)
  File "/usr/lib64/python2.7/site-packages/horovod/tensorflow/__init__.py", line 83, in allreduce
    summed_tensor_compressed = _allreduce(tensor_compressed)
  File "/usr/lib64/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 90, in _allreduce
    return **MPI_LIB.horovod_allreduce**(tensor, name=name)
  File "<string>", line 51, in horovod_allreduce
 
**more detailed logs**

INFO:tensorflow:2018-10-21 07:10:41.649973: loss = 2.593458, step = 64469 (86.659 sec)
INFO:tensorflow:2018-10-21 07:10:41.649989: loss = 2.593458, step = 64469 (86.660 sec)
INFO:tensorflow:2018-10-21 07:11:20.152519: loss = 2.593458, step = 64469 (86.659 sec)
INFO:tensorflow:2018-10-21 07:12:58.641767: loss = 2.593458, step = 64469 (86.660 sec)
INFO:tensorflow:2018-10-21 07:12:58.641761: loss = 2.593458, step = 64469 (86.660 sec)
INFO:tensorflow:2018-10-21 07:09:38.178117: loss = 2.593458, step = 64469 (86.659 sec)
INFO:tensorflow:2018-10-21 07:11:20.152702: loss = 2.593458, step = 64469 (86.659 sec)
INFO:tensorflow:2018-10-21 07:08:57.859448: loss = 2.593458, step = 64469 (86.660 sec)
INFO:tensorflow:2018-10-21 07:09:38.178166: loss = 2.593458, step = 64469 (86.659 sec)
INFO:tensorflow:2018-10-21 07:08:57.859490: loss = 2.593458, step = 64469 (86.660 sec)
INFO:tensorflow:2018-10-21 07:11:37.062297: Saving checkpoints for 64535 into ./model-tmp-1540048389-0/model.ckpt.
INFO:tensorflow:2018-10-21 07:11:41.930417: **Loss for final step: 2.7761219.**
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 87, in main
    transformer.train(train_input_fn, hooks=hooks, steps=steps)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1409, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1239, in run
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1296, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownErrorTraceback (most recent call last):
  File "train.py", line 96, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 87, in main
    transformer.train(train_input_fn, hooks=hooks, steps=steps)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1181, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1409, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1239, in run
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1296, in run
    run_metadata=run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 87, in main
    transformer.train(train_input_fn, hooks=hooks, steps=steps)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1181, in _train_model
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1215, in _train_model_default
    saving_listeners)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1409, in _train_with_estimator_spec
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    _sys.exit(main(argv))
  File "train.py", line 87, in main
    transformer.train(train_input_fn, hooks=hooks, steps=steps)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 356, in train
    run_metadata=run_metadata)
: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
	 [[{{node NmtModel/HorovodAllreduce_NmtModel_Sum_2_0}} = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](NmtModel/Sum_2)]]
	 [[{{node NmtModel/div_203/_5623}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_20531_NmtModel/div_203", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by LiweiPeng** [comment]
@alsrgv Thanks. When I run training on a new dataset, I don't know how many train steps it takes to finish one training loop.  Currently I first try a big number, then use try and error to figure out a proper number. But this is not a good solution.

Any suggestions for better solution? Thanks.

**Comment by alsrgv** [comment]
@LiweiPeng, can you use map-reduce or a simple script to estimate # of examples per epoch, then you can divide by batch size & number of workers.

**Comment by LiweiPeng** [comment]
Thanks @alsrgv . This works

**Comment by Matrix8128** [comment]
another easy way to do this :
dataset = dataset.apply(tf.contrib.data.batch_and_drop_remainder(batch_size))
