### ISSUE TITLE
ImportError :  cannot import name 'load_library'

### ISSUE THREAD

**Issue by ascenoputing** [uber/horovod#611]
hi, the Error appeared when 

import horovod.tensorflow as hvd

**Comment by tgaddair** [comment]
Hey @ascenoputing, can you provide the full stack trace for this error?

**Comment by ascenoputing** [comment]
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    import horovod.tensorflow as hvd
  File "/home/cooper/anaconda3/envs/tensorflow/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 42, in <module>
    from horovod.tensorflow.mpi_ops import allgather
  File "/home/cooper/anaconda3/envs/tensorflow/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 24, in <module>
    from tensorflow.python.framework import load_library
ImportError: cannot import name 'load_library'

I am trying to run the source code GLow
[https://github.com/openai/glow?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more#glow](url)

**Comment by ascenoputing** [comment]
the line created error:
https://github.com/openai/glow/blob/master/train.py#L9

**Comment by tgaddair** [comment]
Glad you got it figured out.  I'm going to go ahead and close the issue for now.
