### ISSUE TITLE
Running Horovod

### ISSUE THREAD

**Issue by abidmalikwaterloo** [uber/horovod#683]
I recently created a new environment for Horovod and got the following error:

```
-bash-4.2$ python tf_cnn_benchmarks.py --num_gpus=4 --batch_size=32 --model=resnet50 -variable_update=horovod --horovod_device=gpu 
Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 60, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 49, in main
    params = benchmark_cnn.setup(params)
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/ToyProblemHorovod/Tensorflow/benchmarks_from_google/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2153, in setup
    import horovod.tensorflow as hvd  # pylint: disable=g-import-not-at-top
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/horovod/tensorflow/__init__.py", line 37, in <module>
    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/horovod/tensorflow/mpi_ops.py", line 58, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/horovod/tensorflow/mpi_ops.py", line 45, in _load_library
    library = load_library.load_op_library(filename)
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/horovod/tensorflow/mpi_lib.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow12OpDefBuilderC1EN4absl11string_viewE
(env) -bash-4.2$ module list
Currently Loaded Modulefiles:
  1) anaconda3/4.2.0     2) gcc/6.4.0           3) cuda/9.0            4) openmpi/3.1.1-gnu
```
Is it the enviornment?

**Comment by abidmalikwaterloo** [comment]
I think there is something wrong with my installation!
```
python
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import horovod.tensorflow as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/horovod/tensorflow/__init__.py", line 37, in <module>
    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/horovod/tensorflow/mpi_ops.py", line 58, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/horovod/tensorflow/mpi_ops.py", line 45, in _load_library
    library = load_library.load_op_library(filename)
  File "/hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /hpcgpfs01/work/amalik/ATLAS_BNL_PANDA/PyTorch_horovod/env/lib/python3.5/site-packages/horovod/tensorflow/mpi_lib.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow12OpDefBuilderC1EN4absl11string_viewE
```
I install both tensorflow and Horovod using pip. I am using python  3, cuda 9 amd openmpi-3.1.1
