### ISSUE TITLE
Crash when using Horovod with Torch0.4 and Py3

### ISSUE THREAD

**Issue by rahul003** [uber/horovod#724]
There's a segfault which shows up in test_torch.py/test_broadcast_state when running tests (i.e. `pytest -v`). 
If this test is run separately (i.e. `pytest -v test/test_torch.py` ), then it passes.

Commit used to build Horovod: 4cf885f8807413720024543f853ff3af06413770
[Crash message](https://pastebin.com/raw/xGzwu6jr)
[Stacktrace from corefile](https://pastebin.com/raw/iifPG6tS)

**Comment by rahul003** [comment]
Considering this happens on the first test of torch after all tensorflow tests are run, does this have to do with some sort of reinitialization of Horovod when we start using Torch?

```
test/test_keras.py::KerasTests::test_load_model PASSED                                                                                                          [  1%]
test/test_keras.py::KerasTests::test_load_model_broadcast PASSED                                                                                                [  3%]
test/test_keras.py::KerasTests::test_load_model_custom_objects PASSED                                                                                           [  5%]
test/test_keras.py::KerasTests::test_load_model_custom_optimizers PASSED                                                                                        [  6%]
test/test_keras.py::KerasTests::test_session <- ../anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py PASSED    [  8%]
test/test_keras.py::KerasTests::test_sparse_as_dense PASSED                                                                                                     [ 10%]
test/test_tensorflow.py::MPITests::test_compression_fp16 PASSED                                                                                                 [ 11%]
test/test_tensorflow.py::MPITests::test_horovod_allgather PASSED                                                                                                [ 13%]
test/test_tensorflow.py::MPITests::test_horovod_allgather_error PASSED                                                                                          [ 15%]
test/test_tensorflow.py::MPITests::test_horovod_allgather_grad PASSED                                                                                           [ 16%]
test/test_tensorflow.py::MPITests::test_horovod_allgather_type_error PASSED                                                                                     [ 18%]
test/test_tensorflow.py::MPITests::test_horovod_allgather_variable_size PASSED                                                                                  [ 20%]
test/test_tensorflow.py::MPITests::test_horovod_allreduce_cpu PASSED                                                                                            [ 22%]
test/test_tensorflow.py::MPITests::test_horovod_allreduce_cpu_fused PASSED                                                                                      [ 23%]
test/test_tensorflow.py::MPITests::test_horovod_allreduce_cpu_gpu_error PASSED                                                                                  [ 25%]
test/test_tensorflow.py::MPITests::test_horovod_allreduce_error PASSED                                                                                          [ 27%]
test/test_tensorflow.py::MPITests::test_horovod_allreduce_gpu PASSED                                                                                            [ 28%]
test/test_tensorflow.py::MPITests::test_horovod_allreduce_gpu_fused PASSED                                                                                      [ 30%]
test/test_tensorflow.py::MPITests::test_horovod_allreduce_grad PASSED                                                                                           [ 32%]
test/test_tensorflow.py::MPITests::test_horovod_allreduce_multi_gpu PASSED                                                                                      [ 33%]
test/test_tensorflow.py::MPITests::test_horovod_allreduce_type_error PASSED                                                                                     [ 35%]
test/test_tensorflow.py::MPITests::test_horovod_broadcast PASSED                                                                                                [ 37%]
test/test_tensorflow.py::MPITests::test_horovod_broadcast_error PASSED                                                                                          [ 38%]
test/test_tensorflow.py::MPITests::test_horovod_broadcast_grad PASSED                                                                                           [ 40%]
test/test_tensorflow.py::MPITests::test_horovod_broadcast_rank_error PASSED                                                                                     [ 42%]
test/test_tensorflow.py::MPITests::test_horovod_broadcast_type_error PASSED                                                                                     [ 44%]
test/test_tensorflow.py::MPITests::test_horovod_rank PASSED                                                                                                     [ 45%]
test/test_tensorflow.py::MPITests::test_horovod_size PASSED                                                                                                     [ 47%]
test/test_tensorflow.py::MPITests::test_session <- ../anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py PASSED [ 49%]
test/test_tensorflow_keras.py::TfKerasTests::test_session <- ../anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py PASSED [ 50%]
test/test_tensorflow_keras.py::TfKerasTests::test_sparse_as_dense PASSED                                                                                        [ 52%]
test/test_tensorflow_keras.py::TfKerasTests::test_train_model PASSED
test/test_torch.py::TorchTests::test_broadcast_state *** Error in `/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/python': free(): invalid pointer: 0x00007faf204ff358 ***
```

```
#12 horovod::common::Status::~Status (this=0x7ffd0a21c470, __in_chrg=<optimized out>) at /home/ubuntu/horovod/horovod/torch/../common/common.h:37
#13 horovod::torch::DoBroadcast<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor> (tensor=0x55db78d699a0,
    output=0x55db78d699a0, root_rank=root_rank@entry=0, name=0x0) at /home/ubuntu/horovod/horovod/torch/mpi_ops.cc:161
```

Relevant code: https://github.com/uber/horovod/blob/4cf885f8807413720024543f853ff3af06413770/horovod/common/operations.cc#L2198

Is there something that needs to be fixed here?

**Comment by rahul003** [comment]
I actually see two different errors here strangely.

Sometimes, this one below and other times the one mentioned in the above comments.
```
#0  0x00007f83e593d428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f83e593f02a in __GI_abort () at abort.c:89
#2  0x00007f83e597f7ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f83e5a98ed8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f83e598837a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7f83e5a95caf "free(): invalid pointer", action=3) at malloc.c:5006
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3867
#5  0x00007f83e598c53c in __GI___libc_free (mem=<optimized out>) at malloc.c:2968
#6  0x00007f83b1f3c64c in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor>, std::allocator<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor> >, (__gnu_cxx::_Lock_policy)2> >::deallocate (this=<optimized out>, __p=0x0) at /usr/include/c++/5/ext/new_allocator.h:110
#7  std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor>, std::allocator<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor> >, (__gnu_cxx::_Lock_policy)2> > >::deallocate (__a=..., __n=1, __p=0x0) at /usr/include/c++/5/bits/alloc_traits.h:517
#8  std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor>, std::allocator<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor> >, (__gnu_cxx::_Lock_policy)2> > >::~__allocated_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/allocated_ptr.h:72
#9  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor>, std::allocator<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor> >, THFloatTensor*&> (__a=..., this=<synthetic pointer>) at /usr/include/c++/5/bits/shared_ptr_base.h:615
#10 std::__shared_ptr<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor>, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor> >, THFloatTensor*&> (__a=..., __tag=..., this=<synthetic pointer>) at /usr/include/c++/5/bits/shared_ptr_base.h:1097
#11 std::shared_ptr<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor> >::shared_ptr<std::allocator<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor> >, THFloatTensor*&> (__a=..., __tag=...,
    this=<synthetic pointer>) at /usr/include/c++/5/bits/shared_ptr.h:319
#12 std::allocate_shared<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor>, std::allocator<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor> >, THFloatTensor*&> (__a=...)
    at /usr/include/c++/5/bits/shared_ptr.h:620
#13 std::make_shared<horovod::torch::TorchTensor<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor>, THFloatTensor*&> () at /usr/include/c++/5/bits/shared_ptr.h:636
#14 horovod::torch::DoAllgather<(horovod::common::MPIDataType)7, (horovod::common::DeviceType)0, THFloatTensor> (tensor=0x7f833bb4bf98 <PyObject_Call@got.plt>, output=0x55db78d699a0, name=0x55db78d699a0 "@\350\335x\333U") at /home/ubuntu/horovod/horovod/torch/mpi_ops.cc:110
#15 0x00007f83b1c4f31a in _cffi_f_horovod_torch_broadcast_async_torch_FloatTensor (self=<optimized out>, args=<optimized out>) at build/horovod/torch/mpi_lib/_mpi_lib.c:2615
#16 0x000055da9fa4ea61 in PyCFunction_Call ()
#17 0x000055da9fa4b99e in PyObject_Call ()
#18 0x00007f83331473cc in THPModule_safeCall (_unused=<optimized out>, args=0x7f82ac3b8620, kwargs=0x7f82740b8990) at torch/csrc/Module.cpp:149
#19 0x000055da9fa4e9f6 in PyCFunction_Call ()
#20 0x000055da9fb02fdb in _PyEval_EvalF
```

**Comment by rahul003** [comment]
I flipped the tests around. Ran pytorch first then keras. This time it crashed at Keras 
```test/test_keras.py::KerasTests::test_load_model_broadcast Segmentation fault (core dumped)```

**Comment by rahul003** [comment]
Did you run the tests with master too?

**Comment by alsrgv** [comment]
@rahul003, master runs daily tests every day, and I don't see this issue happening.

**Comment by alsrgv** [comment]
@rahul003, I may have found a solution (and the reasoning behind it).  See #730.

**Comment by rahul003** [comment]
Makes sense, thanks!
