### ISSUE TITLE
Horovod with latest PyTorch src

### ISSUE THREAD

**Issue by jaliyae** [uber/horovod#767]
Hi, 

I tried using Horovod with the current PyTorch src build and noticed the following error in all PyTorch samples, which seems to need an update to the horovod/torch. Is this a known issue?
```
Traceback (most recent call last):
  File "pytorch_mnist.py", line 165, in <module>
    train(epoch)
  File "pytorch_mnist.py", line 120, in train
    optimizer.step()
  File "/usr/local/anaconda3/envs/abc_pytorch1/lib/python3.7/site-packages/horovod/torch/__init__.py", line 111, in step
    self.synchronize()
  File "/usr/local/anaconda3/envs/abc_pytorch1/lib/python3.7/site-packages/horovod/torch/__init__.py", line 107, in synchronize
    p.grad.data.set_(self._compression.decompress(output, ctx))
RuntimeError: set_storage_offset is not allowed on Tensor created from .data or .detach()
```
Thank you

**Comment by alsrgv** [comment]
@jaliyae, could you install Horovod from master:
```
$ [flags] pip install git+https://github.com/uber/horovod@master
```

**Comment by jaliyae** [comment]
@alsrgv It worked with the build from master as you mentioned. Thank you!
