### ISSUE TITLE
Install horovod with pytorch only

### ISSUE THREAD

**Issue by xinli94** [uber/horovod#783]
Hi,

I am trying to build dockerfile, in which I want to install horovod with **cuda10** and **pytorch only**. But it looks like even if I set `HOROVOD_WITH_TENSORFLOW=0`, tensorflow is still required at some point. Is it possible to turn off any tensorflow related requirements?

For your information:
RTX does not work with cuda9 well, and cuda10 breaks tensorflow. That's why I want pytorch-only horovod. Or is there any other way to fix this? 

```
Step 14/21 : RUN ldconfig /usr/local/cuda-10.0/targets/x86_64-linux/lib/stubs &&     HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_CUDA_HOME=/usr/local/cuda-10.0/ HOROVOD_WITH_TENSORFLOW=0 HOROVOD_WITH_PYTORCH=1 pip install --no-cache-dir horovod &&     ldconfig
 ---> Running in 0c0e38fcb11a
Collecting horovod
  Downloading https://files.pythonhosted.org/packages/17/1a/3e836e3f659d3b331afcb679f84c46c8d489c2b8c21b1d85a99ac31d3480/horovod-0.15.2.tar.gz (119kB)
Requirement already satisfied: cffi>=1.4.0 in /miniconda/envs/py36/lib/python3.6/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in /miniconda/envs/py36/lib/python3.6/site-packages (from cffi>=1.4.0->horovod) (2.19)
Installing collected packages: horovod
  Running setup.py install for horovod: started
    Running setup.py install for horovod: finished with status 'error'
    Complete output from command /miniconda/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-njafe9z1/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ae8o0oz1/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
    creating build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
    creating build/lib.linux-x86_64-3.6/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
    creating build/lib.linux-x86_64-3.6/horovod/_keras
    copying horovod/_keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/_keras
    copying horovod/_keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/_keras
    creating build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/compression.py -> build/lib.linux-x86_64-3.6/horovod/torch
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/compression.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow/keras
    running build_ext
    gcc -pthread -B /miniconda/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/miniconda/envs/py36/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /miniconda/envs/py36/compiler_compat -L/miniconda/envs/py36/lib -Wl,-rpath=/miniconda/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
    gcc -pthread -B /miniconda/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/miniconda/envs/py36/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_link_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_link_flags.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /miniconda/envs/py36/compiler_compat -L/miniconda/envs/py36/lib -Wl,-rpath=/miniconda/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Wl,--version-script=horovod.lds build/temp.linux-x86_64-3.6/test_compile/test_link_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_link_flags.so
    gcc -pthread -B /miniconda/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/usr/local/cuda-10.0//include -I/miniconda/envs/py36/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cuda.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cuda.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /miniconda/envs/py36/compiler_compat -L/miniconda/envs/py36/lib -Wl,-rpath=/miniconda/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cuda.o -L/usr/local/cuda-10.0//lib -L/usr/local/cuda-10.0//lib64 -lcudart -o build/temp.linux-x86_64-3.6/test_compile/test_cuda.so
    gcc -pthread -B /miniconda/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/usr/local/cuda-10.0//include -I/miniconda/envs/py36/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_nccl.cc -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /miniconda/envs/py36/compiler_compat -L/miniconda/envs/py36/lib -Wl,-rpath=/miniconda/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_nccl.o -L/usr/local/cuda-10.0//lib -L/usr/local/cuda-10.0//lib64 -lnccl_static -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.so
    error: import tensorflow failed, is it installed?

    Traceback (most recent call last):
      File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/miniconda/envs/py36/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/miniconda/envs/py36/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-njafe9z1/horovod/setup.py", line 54, in check_tf_version
        import tensorflow as tf
      File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
      File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/miniconda/envs/py36/lib/python3.6/imp.py", line 243, in load_module
        return load_dynamic(name, filename, file)
      File "/miniconda/envs/py36/lib/python3.6/imp.py", line 343, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


    Failed to load the native TensorFlow runtime.

    See https://www.tensorflow.org/install/errors

    for some common reasons and solutions.  Include the entire stack trace
    above this error message when asking for help.


    ----------------------------------------
Command "/miniconda/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-njafe9z1/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ae8o0oz1/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-njafe9z1/horovod/
The command '/bin/sh -c ldconfig /usr/local/cuda-10.0/targets/x86_64-linux/lib/stubs &&     HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_CUDA_HOME=/usr/local/cuda-10.0/ HOROVOD_WITH_TENSORFLOW=0 HOROVOD_WITH_PYTORCH=1 pip install --no-cache-dir horovod &&     ldconfig' returned a non-zero code: 1
```

Thanks,
Xin

**Comment by xinli94** [comment]
Sorry I already fixed my dockerfile: just set `HOROVOD_WITHOUT_TENSORFLOW=1` and it works..
