### ISSUE TITLE
Fail to install Horovod on Ubuntu 16.04

### ISSUE THREAD

**Issue by HugoPu** [uber/horovod#791]
I failed to install Horovod on ubuntu 16.04, nccl2 and openmpi4.0 were installed. The following is the error info.
```
HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod
Collecting horovod
  Downloading https://files.pythonhosted.org/packages/17/1a/3e836e3f659d3b331afcb679f84c46c8d489c2b8c21b1d85a99ac31d3480/horovod-0.15.2.tar.gz (119kB)
    100% |████████████████████████████████| 122kB 30kB/s
Requirement already satisfied: cffi>=1.4.0 in /home/phtadmin/anaconda3/envs/tf_hugo/lib/python3.5/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in /home/phtadmin/anaconda3/envs/tf_hugo/lib/python3.5/site-packages (from cffi>=1.4.0->horovod) (2.19)
Exception:
Traceback (most recent call last):
  File "/home/phtadmin/anaconda3/envs/tf_hugo/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/home/phtadmin/anaconda3/envs/tf_hugo/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/home/phtadmin/anaconda3/envs/tf_hugo/lib/python3.5/site-packages/pip/_internal/wheel.py", line 848, in build
    assert building_is_possible
AssertionError
````

**Comment by HugoPu** [comment]
`pip install horovod` works for me. But when I installed nccl2 and openmpi4.0, there were no errors to display, why can't I use `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod` to install horovod

**Comment by alsrgv** [comment]
@HugoPu, you should install with NCCL if you have GPUs.  Can you try upgrading `pip` using `pip install -U pip` while in conda environment, before installing Horovod with `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod`?

**Comment by HugoPu** [comment]
> @HugoPu, you should install with NCCL if you have GPUs. Can you try upgrading `pip` using `pip install -U pip` while in conda environment, before installing Horovod with `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod`?

After update pip from 19.0 to 19.0.1, it seems work for me, thank you!

```
(tf_hugo) phtadmin@phtadmin-HP-Z420-Workstation:~$ pip install -U pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/46/dc/7fd5df840efb3e56c8b4f768793a237ec4ee59891959d6a215d63f727023/pip-19.0.1-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 27kB/s
Installing collected packages: pip
  Found existing installation: pip 19.0
    Uninstalling pip-19.0:
      Successfully uninstalled pip-19.0
Successfully installed pip-19.0.1
(tf_hugo) phtadmin@phtadmin-HP-Z420-Workstation:~$ HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod
Requirement already satisfied: horovod in ./anaconda3/envs/tf_hugo/lib/python3.5/site-packages (0.15.2)
Requirement already satisfied: cffi>=1.4.0 in ./anaconda3/envs/tf_hugo/lib/python3.5/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in ./anaconda3/envs/tf_hugo/lib/python3.5/site-packages (from cffi>=1.4.0->horovod) (2.19)
(tf_hugo) phtadmin@phtadmin-HP-Z420-Workstation:~$ pip uninstall horovod
Uninstalling horovod-0.15.2:
  Would remove:
    /home/phtadmin/anaconda3/envs/tf_hugo/lib/python3.5/site-packages/horovod-0.15.2.dist-info/*
    /home/phtadmin/anaconda3/envs/tf_hugo/lib/python3.5/site-packages/horovod/*
Proceed (y/n)? y
  Successfully uninstalled horovod-0.15.2
(tf_hugo) phtadmin@phtadmin-HP-Z420-Workstation:~$ pip -V
pip 19.0.1 from /home/phtadmin/anaconda3/envs/tf_hugo/lib/python3.5/site-packages/pip (python 3.5)
(tf_hugo) phtadmin@phtadmin-HP-Z420-Workstation:~$ HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod
Collecting horovod
  Downloading https://files.pythonhosted.org/packages/17/1a/3e836e3f659d3b331afcb679f84c46c8d489c2b8c21b1d85a99ac31d3480/horovod-0.15.2.tar.gz (119kB)
    100% |████████████████████████████████| 122kB 44kB/s
Requirement already satisfied: cffi>=1.4.0 in ./anaconda3/envs/tf_hugo/lib/python3.5/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in ./anaconda3/envs/tf_hugo/lib/python3.5/site-packages (from cffi>=1.4.0->horovod) (2.19)
Installing collected packages: horovod
  Running setup.py install for horovod ... done
Successfully installed horovod-0.15.2
```
