### ISSUE TITLE
Running horovod spark on local system

### ISSUE THREAD

**Issue by abimur-123** [uber/horovod#803]
I've been trying to setup horovod with spark from the example mentioned [here](https://github.com/uber/horovod/blob/master/docs/spark.md).

I get the following error when I try to run the `magic_number` function

```
Exception happened during processing of request from ('127.0.0.1', 40114)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/horovod/spark/util/network.py", line 112, in handle
    resp = server._handle(req, self.client_address)
  File "/usr/local/lib/python3.6/site-packages/horovod/spark/driver/driver_service.py", line 148, in _handle
    return TaskHostHashIndicesResponse(self._task_host_hash_indices[req.host_hash])
KeyError: '<System_name>:12'
```

I setup a simple Spark session and tried running it on a notebook, but encountered the same error - 
```
from pyspark.sql import SparkSession
spark =  SparkSession.builder.appName("jobtest08").\
        config("spark.executor.instances", "1").\
        config('spark.executor.cores', '2').\
        config("spark.default.parallelism", '1').\
        getOrCreate()

sc = spark.sparkContext
```

Am I doing something wrong with my setup here?

**Comment by alsrgv** [comment]
@abimur-123, which version of MPI are you using?  Horovod-in-PySpark currently works exclusively with Open MPI and we recommend 3.1.2 or 4.0.0.

**Comment by abimur-123** [comment]
@alsrgv Yeah, that was it. Was using an older version of MPI. It works now

Cheers!
