### ISSUE TITLE
Error while running spark end-to-end example

### ISSUE THREAD

**Issue by abimur-123** [uber/horovod#811]
I am currently trying to run the end-to-end example provided on the spark page [here](https://github.com/uber/horovod/blob/master/docs/spark.md) and get the following error - 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/compat.py", line 29, in fspath
    return path_type.__fspath__(path)
AttributeError: type object '_io.BytesIO' has no attribute '__fspath__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "keras_spark_rossmann.py", line 377, in <module>
    model_bytes = serialize_model(model)
  File "keras_spark_rossmann.py", line 339, in serialize_model
    with h5py.File(bio) as f:
  File "/usr/local/lib/py`thon3.5/dist-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/compat.py", line 42, in fspath
    + path_type.__name__)
TypeError: expected str, bytes or os.PathLike object, not BytesIO
```

`keras version = 2.2.2`

**Comment by alsrgv** [comment]
@abimur-123, can you upgrade h5py to latest?
