### ISSUE TITLE
ERROR: ncclAllReduce failed: invalid data type

### ISSUE THREAD

**Issue by asanakoy** [uber/horovod#91]
Getting ncclAllReduce failed: invalid data type error when running training with horovod on 2 GPUs on single machine. 
```
mpirun -np 2 -x PATH -x LD_LIBRARY_PATH -x CUDA_VISIBLE_DEVICES -H localhost:2 python train_image_classifier_joint_horovod.py
```

Fail at the first call of 
```
sess.run([train_op, global_step],
                options=trace_run_options,
                 run_metadata=run_metadata)
```

```
Traceback (most recent call last):
  File "train_image_classifier_joint_horovod.py", line 778, in <module>
    tf.app.run()
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier_joint_horovod.py", line 774, in main
    session_config=session_config)
  File "/home/asanakoy/workspace/art/art/slimext/learning_horovod.py", line 194, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/home/asanakoy/workspace/art/art/slimext/learning.py", line 79, in train_step
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 892, in run
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 827, in run
    return self._sess.run(*args, **kwargs)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: ncclAllReduce failed: invalid data type
         [[Node: DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_2_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/AddN_2)]]
         [[Node: train_op/_653 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1601_train_op", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:
0"]()]]

Caused by op u'DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_2_0', defined at:
  File "train_image_classifier_joint_horovod.py", line 778, in <module>
    tf.app.run()
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier_joint_horovod.py", line 708, in main
    grad_updates = optimizer.minimize(total_loss, var_list=variables_to_train)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 180, in compute_gradients
    device_sparse=self._device_sparse)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 76, in allreduce
    summed_tensor = _allreduce(tensor)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 145, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 37, in horovod_allreduce
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): ncclAllReduce failed: invalid data type
         [[Node: DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_2_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/AddN_2)]]
         [[Node: train_op/_653 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1601_train_op", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:
0"]()]]

```

Any ideas why it is happening?

But the same script works well with `-np 1`.
OS: CentOS / Ubuntu
Open MPI 3.0.0
Nvidia driver 367.48
CUDA 8.0
NCCL 2.0.5
Tensorflow 1.4.0
Horovod 0.11.0

**Comment by alsrgv** [comment]
@asanakoy, can you add `-x NCCL_DEBUG=INFO` to your `mpirun`? It may help reveal some NCCL debug messages about this error.

**Comment by asanakoy** [comment]
Full log with `-x NCCL_DEBUG=INFO`.

```
INFO NCCL debug level set to INFO
INFO NCCL debug level set to INFO
INFO rank 1 using buffSize = 2097152
INFO rank 1 using device 1 (0000:82:00.0)
INFO rank 0 using buffSize = 2097152
INFO rank 0 using device 0 (0000:05:00.0)
INFO rank access 0 -> 0 via common device
INFO rank access 1 -> 0 via zero-copy host mem
INFO rank access 1 -> 1 via common device
INFO rank access 0 -> 1 via zero-copy host mem
INFO Global device memory space is disabled
INFO Global device memory space is disabled
WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

WARN src/common_coll.h:42 AllReduce : invalid type 7

2017-11-14 07:38:21.818966: W tensorflow/core/kernels/queue_base.cc:295] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2017-11-14 07:38:21.959943: W tensorflow/core/kernels/queue_base.cc:295] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
-1
-1
Traceback (most recent call last):
  File "train_image_classifier_joint_horovod.py", line 778, in <module>
    tf.app.run()
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier_joint_horovod.py", line 774, in main
    session_config=session_config)
  File "/home/asanakoy/workspace/art/art/slimext/learning_horovod.py", line 194, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/home/asanakoy/workspace/art/art/slimext/learning.py", line 79, in train_step
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 892, in run
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 827, in run
Traceback (most recent call last):
  File "train_image_classifier_joint_horovod.py", line 778, in <module>
    return self._sess.run(*args, **kwargs)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: ncclAllReduce failed: invalid data type
         [[Node: DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_2_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/AddN_2)]]
         [[Node: train_op/_747 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1926_train_op", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_2_0', defined at:
  File "train_image_classifier_joint_horovod.py", line 778, in <module>
    tf.app.run()
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier_joint_horovod.py", line 708, in main
    grad_updates = optimizer.minimize(total_loss, var_list=variables_to_train)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 180, in compute_gradients
    device_sparse=self._device_sparse)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 76, in allreduce
    summed_tensor = _allreduce(tensor)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 145, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 37, in horovod_allreduce
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): ncclAllReduce failed: invalid data type
         [[Node: DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_2_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/AddN_2)]]
         [[Node: train_op/_747 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1926_train_op", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

    tf.app.run()
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier_joint_horovod.py", line 774, in main
    session_config=session_config)
  File "/home/asanakoy/workspace/art/art/slimext/learning_horovod.py", line 194, in train
    sess, train_op, global_step, train_step_kwargs)
  File "/home/asanakoy/workspace/art/art/slimext/learning.py", line 79, in train_step
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 892, in run
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 827, in run
    return self._sess.run(*args, **kwargs)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: ncclAllReduce failed: invalid data type
         [[Node: DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_2_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/AddN_2)]]
         [[Node: train_op/_653 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1601_train_op", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_2_0', defined at:
  File "train_image_classifier_joint_horovod.py", line 778, in <module>
    tf.app.run()
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier_joint_horovod.py", line 708, in main
    grad_updates = optimizer.minimize(total_loss, var_list=variables_to_train)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 180, in compute_gradients
    device_sparse=self._device_sparse)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 76, in allreduce
    summed_tensor = _allreduce(tensor)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 145, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 37, in horovod_allreduce
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): ncclAllReduce failed: invalid data type
         [[Node: DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_2_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/AddN_2)]]
         [[Node: train_op/_653 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1601_train_op", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Exception in thread Data_loop:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/asanakoy/workspace/art/art/datasets/data_loop_pytorch.py", line 56, in data_loop_fn
    enqueue_many_op, images_input, labels_input)
  File "/home/asanakoy/workspace/art/art/datasets/data_loop_pytorch.py", line 18, in data_loop
    label_input: labels})
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1047, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

Exception in thread Data_loop:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/asanakoy/workspace/art/art/datasets/data_loop_pytorch.py", line 56, in data_loop_fn
    enqueue_many_op, images_input, labels_input)
  File "/home/asanakoy/workspace/art/art/datasets/data_loop_pytorch.py", line 18, in data_loop
    label_input: labels})
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1047, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[654,1],0]
  Exit code:    1
--------------------------------------------------------------------------


```

**Comment by alsrgv** [comment]
@asanakoy, the NCCL log does not look like NCCL 2.0.5. Do you happen to have NCCL 1.x installed on your system as well?

Can you paste the output of this as well:
```bash
$ ldd `find /home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages | grep horovod/tensorflow/mpi_lib.so`
```

**Comment by asanakoy** [comment]
```
:~$ ldd `find /home/asanakoy/.venvs/tf_r1/lib/python2.7/site-packages | grep horovod/tensorflow/mpi_lib.so`
        linux-vdso.so.1 =>  (0x00007ffd17ff6000)
        libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00007f9c382ac000)
        libnccl.so.2 => /home/asanakoy/.local/opt/nccl_2.0.5-3+cuda8.0_amd64/lib/libnccl.so.2 (0x00007f9c2bd42000)
        libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007f9c2b977000)
        libmpi.so.40 => /usr/local/lib/libmpi.so.40 (0x00007f9c2b67d000)
        libtensorflow_framework.so => not found
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9c2b373000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f9c2b071000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9c2ae5a000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9c2ac3e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9c2a87d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f9c2a678000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f9c2a470000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9c3878b000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f9c2a26d000)
        libopen-rte.so.40 => /usr/local/lib/libopen-rte.so.40 (0x00007f9c29fbb000)
        libopen-pal.so.40 => /usr/local/lib/libopen-pal.so.40 (0x00007f9c29cba000)
        libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f9c29aae000)
        libudev.so.1 => /lib64/libudev.so.1 (0x00007f9c29a98000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f9c29882000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007f9c2967c000)
        libdw.so.1 => /lib64/libdw.so.1 (0x00007f9c29435000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007f9c29230000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00007f9c29019000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f9c28df4000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f9c28be4000)
```

**Comment by alsrgv** [comment]
@asanakoy, did you install TensorFlow 1.4.0 from source, or from the official pip package?

**Comment by asanakoy** [comment]
@alsrgv from official pip. Should I buid it from source?

**Comment by asanakoy** [comment]
@alsrgv is it necessary to build Tensorflow with MPI support ?

**Comment by alsrgv** [comment]
@asanakoy, no, you don't need to build TensorFlow - the version from the pip should work fine.  I'm trying to repro it on my machine, but to no avail for now.

Can you confirm whether this [example code](https://raw.githubusercontent.com/uber/horovod/master/examples/tensorflow_mnist.py) crashes as well?

Also, can you run this (may take a while) and share the output:
```bash
$ find / 2>/dev/null | grep libnccl.so
```

**Comment by asanakoy** [comment]
@alsrgv [example code](https://raw.githubusercontent.com/uber/horovod/master/examples/tensorflow_mnist.py) works well.  


My code is different because I have to call `sess.run(equeue_op)` in a separate thread where I read data from disk. 
It's not allowed to explicitly call  `MonitoredTrainingSession.run()`  therefore I use `MonitoredTrainingSession._tf_sess().run()` as I don't have any other option.

**Comment by asanakoy** [comment]
@alsrgv Also I reinstalled `horovod` whithout `nccl` and it doesn't fail. Will it be much slower without `nccl` ?

**Comment by alsrgv** [comment]
@asanakoy, you can check the scaling that you're getting without NCCL. Does your code use NCCL directly? Did you get an output from that `find` command?

**Comment by asanakoy** [comment]
@alsrgv I don't use NCCL directly, it is used only be horovod.
I'm still running that `find`.

**Comment by alsrgv** [comment]
@asanakoy, could you also try to add `-x LD_DEBUG=all` to your run with NCCL?  That should help us understand which libraries are loaded.

**Comment by asanakoy** [comment]
@alsrgv I figured out what was the problem. `-x LD_DEBUG=all` helped, thank you! 

I use pytorch's `Dataset` to load data. Pytorch depends on `libnccl.so.1` and has it in the `site-packages/torch/lib`. Horovod requires NCCL v2. And different versions of the same library screw everything.

After I removed pytorch from the code, everything works well.

**Comment by alsrgv** [comment]
@asanakoy, congrats!

**Comment by alsrgv** [comment]
I will add this to the troubleshooting on the next doc update.

**Comment by asanakoy** [comment]
You can also add a solution how to use Horovod with NCCL 2 and Pytorch.
By default pytorch is linked to system-default nccl (version 1). 
I have build it from sources `NCCL_ROOT_DIR=$NCCL_PATH CUDNN_LIB_DIR=$CUDNN_LIB_DIR  CUDNN_INCLUDE_DIR=$CUDNN_INC_DIR python setup.py install` with NCCL 2.0.5.  
Now horovod doesn't fail.

**Comment by alsrgv** [comment]
@asanakoy, that's a neat idea, thanks!

**Comment by alsrgv** [comment]
As of 0.12.0+, Horovod will not conflict with PyTorch's own NCCL 1.x.

If you're using Horovod 0.12.0+ and still seeing `ncclAllReduce failed: invalid data type`, you likely have NCCL 1.3.4 **conda** package.  The solution is to `conda remove nccl`.
